--------------------------------------------------------
--  File created - sobota-listopada-16-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ADRESY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SCHRONISKO"."ADRESY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 46 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PRACOWNICY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SCHRONISKO"."PRACOWNICY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 76 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table ADRESY
--------------------------------------------------------

  CREATE TABLE "SCHRONISKO"."ADRESY" 
   (	"ID_ADRESU" NUMBER, 
	"MIASTO" VARCHAR2(50 BYTE), 
	"KOD_POCZTOWY" VARCHAR2(10 BYTE), 
	"ULICA" VARCHAR2(100 BYTE), 
	"NUMER_DOMU" VARCHAR2(10 BYTE), 
	"NUMER_MIESZKANIA" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DARCZYNCY
--------------------------------------------------------

  CREATE TABLE "SCHRONISKO"."DARCZYNCY" 
   (	"ID" NUMBER, 
	"NAZWA_UZYTKOWNIKA" VARCHAR2(50 BYTE), 
	"IMIE" VARCHAR2(50 BYTE), 
	"NAZWISKO" VARCHAR2(50 BYTE), 
	"MAIL" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KOJCE
--------------------------------------------------------

  CREATE TABLE "SCHRONISKO"."KOJCE" 
   (	"KOJEC_ID" NUMBER, 
	"WIELKOSC" VARCHAR2(20 BYTE), 
	"NUMER" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table OSOBY_ADOPTUJACE
--------------------------------------------------------

  CREATE TABLE "SCHRONISKO"."OSOBY_ADOPTUJACE" 
   (	"ID" NUMBER, 
	"IMIE" VARCHAR2(50 BYTE), 
	"NAZWISKO" VARCHAR2(50 BYTE), 
	"ADRES_ID" NUMBER, 
	"NUMER_TELEFONU" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRACOWNICY
--------------------------------------------------------

  CREATE TABLE "SCHRONISKO"."PRACOWNICY" 
   (	"ID" NUMBER, 
	"IMIE" VARCHAR2(50 BYTE), 
	"NAZWISKO" VARCHAR2(50 BYTE), 
	"PENSJA" NUMBER(10,2), 
	"STANOWISKO" VARCHAR2(100 BYTE), 
	"ADRES_ID" NUMBER, 
	"DATA_ZATRUDNIENIA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRACOWNIK_ZWIERZETA
--------------------------------------------------------

  CREATE TABLE "SCHRONISKO"."PRACOWNIK_ZWIERZETA" 
   (	"PRACOWNIK_ID" NUMBER, 
	"ZWIERZE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REJESTR_ADOPCJI
--------------------------------------------------------

  CREATE TABLE "SCHRONISKO"."REJESTR_ADOPCJI" 
   (	"ID_ADOPCJI" NUMBER, 
	"DATA_ADOPCJI" DATE, 
	"OSOBA_ADOPTUJACA" NUMBER, 
	"ZWIERZE_ID" NUMBER, 
	"PRACOWNIK_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REJESTR_DAROWIZN
--------------------------------------------------------

  CREATE TABLE "SCHRONISKO"."REJESTR_DAROWIZN" 
   (	"ID" NUMBER, 
	"DARCZYNCA_ID" NUMBER, 
	"KWOTA" NUMBER(10,2), 
	"DATA" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ZWIERZETA
--------------------------------------------------------

  CREATE TABLE "SCHRONISKO"."ZWIERZETA" 
   (	"ID" NUMBER, 
	"IMIE" VARCHAR2(50 BYTE), 
	"RASA" VARCHAR2(50 BYTE), 
	"PLEC" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(50 BYTE), 
	"KOJEC_ID" NUMBER, 
	"DATA_PRZYJECIA" DATE, 
	"WIEK" NUMBER, 
	"TYP" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SCHRONISKO.ADRESY
SET DEFINE OFF;
Insert into SCHRONISKO.ADRESY (ID_ADRESU,MIASTO,KOD_POCZTOWY,ULICA,NUMER_DOMU,NUMER_MIESZKANIA) values ('1','Warszawa','00-001','Marsza³kowska','1','1');
Insert into SCHRONISKO.ADRESY (ID_ADRESU,MIASTO,KOD_POCZTOWY,ULICA,NUMER_DOMU,NUMER_MIESZKANIA) values ('2','Warszawa','00-002','Nowy Œwiat','2',null);
Insert into SCHRONISKO.ADRESY (ID_ADRESU,MIASTO,KOD_POCZTOWY,ULICA,NUMER_DOMU,NUMER_MIESZKANIA) values ('3','Kraków','30-001','Floriañska','5',null);
Insert into SCHRONISKO.ADRESY (ID_ADRESU,MIASTO,KOD_POCZTOWY,ULICA,NUMER_DOMU,NUMER_MIESZKANIA) values ('4','Kraków','30-002','Grodzka','3','2');
Insert into SCHRONISKO.ADRESY (ID_ADRESU,MIASTO,KOD_POCZTOWY,ULICA,NUMER_DOMU,NUMER_MIESZKANIA) values ('5','Rzesz??w','80-001','Krotka','10','2');
REM INSERTING into SCHRONISKO.DARCZYNCY
SET DEFINE OFF;
REM INSERTING into SCHRONISKO.KOJCE
SET DEFINE OFF;
Insert into SCHRONISKO.KOJCE (KOJEC_ID,WIELKOSC,NUMER) values ('1','Ma³y','K01DOG');
Insert into SCHRONISKO.KOJCE (KOJEC_ID,WIELKOSC,NUMER) values ('2','Œredni','K02DOG');
Insert into SCHRONISKO.KOJCE (KOJEC_ID,WIELKOSC,NUMER) values ('3','Du¿y','K03DOG');
Insert into SCHRONISKO.KOJCE (KOJEC_ID,WIELKOSC,NUMER) values ('4','Ma³y','K04DOG');
Insert into SCHRONISKO.KOJCE (KOJEC_ID,WIELKOSC,NUMER) values ('5','Œredni','K05DOG');
Insert into SCHRONISKO.KOJCE (KOJEC_ID,WIELKOSC,NUMER) values ('6','Du¿y','K06DOG');
Insert into SCHRONISKO.KOJCE (KOJEC_ID,WIELKOSC,NUMER) values ('7','Ma³y','K07DOG');
Insert into SCHRONISKO.KOJCE (KOJEC_ID,WIELKOSC,NUMER) values ('8','Œredni','K08DOG');
Insert into SCHRONISKO.KOJCE (KOJEC_ID,WIELKOSC,NUMER) values ('9','Du¿y','K09DOG');
Insert into SCHRONISKO.KOJCE (KOJEC_ID,WIELKOSC,NUMER) values ('10','Œredni','K10DOG');
Insert into SCHRONISKO.KOJCE (KOJEC_ID,WIELKOSC,NUMER) values ('11','Ma³y','K11CAT');
Insert into SCHRONISKO.KOJCE (KOJEC_ID,WIELKOSC,NUMER) values ('12','Œredni','K12CAT');
Insert into SCHRONISKO.KOJCE (KOJEC_ID,WIELKOSC,NUMER) values ('13','Du¿y','K13CAT');
REM INSERTING into SCHRONISKO.OSOBY_ADOPTUJACE
SET DEFINE OFF;
REM INSERTING into SCHRONISKO.PRACOWNICY
SET DEFINE OFF;
Insert into SCHRONISKO.PRACOWNICY (ID,IMIE,NAZWISKO,PENSJA,STANOWISKO,ADRES_ID,DATA_ZATRUDNIENIA) values ('1','Anna','Kowalska','3000','Opiekun Zwierz¹t','1',to_date('21/05/10','RR/MM/DD'));
Insert into SCHRONISKO.PRACOWNICY (ID,IMIE,NAZWISKO,PENSJA,STANOWISKO,ADRES_ID,DATA_ZATRUDNIENIA) values ('2','Jan','Nowak','3500','Sprz¹tacz','2',to_date('20/11/15','RR/MM/DD'));
Insert into SCHRONISKO.PRACOWNICY (ID,IMIE,NAZWISKO,PENSJA,STANOWISKO,ADRES_ID,DATA_ZATRUDNIENIA) values ('3','Marta','Wiœniewska','3200','Koordynator Adopcji','3',to_date('22/02/20','RR/MM/DD'));
Insert into SCHRONISKO.PRACOWNICY (ID,IMIE,NAZWISKO,PENSJA,STANOWISKO,ADRES_ID,DATA_ZATRUDNIENIA) values ('4','Tomasz','Wójcik','5000','Weterynarz','4',to_date('19/08/01','RR/MM/DD'));
Insert into SCHRONISKO.PRACOWNICY (ID,IMIE,NAZWISKO,PENSJA,STANOWISKO,ADRES_ID,DATA_ZATRUDNIENIA) values ('5','Ewa','Zieliñska','3100','Opiekun Zwierz¹t','5',to_date('21/03/18','RR/MM/DD'));
Insert into SCHRONISKO.PRACOWNICY (ID,IMIE,NAZWISKO,PENSJA,STANOWISKO,ADRES_ID,DATA_ZATRUDNIENIA) values ('6','Kamil','Kowalski','2800','Sprz¹tacz','1',to_date('23/03/15','RR/MM/DD'));
Insert into SCHRONISKO.PRACOWNICY (ID,IMIE,NAZWISKO,PENSJA,STANOWISKO,ADRES_ID,DATA_ZATRUDNIENIA) values ('7','Magda','Nowak','2800','Sprz¹tacz','2',to_date('23/06/10','RR/MM/DD'));
Insert into SCHRONISKO.PRACOWNICY (ID,IMIE,NAZWISKO,PENSJA,STANOWISKO,ADRES_ID,DATA_ZATRUDNIENIA) values ('8','Michal','Zielinski','5000','Weterynarz','3',to_date('24/11/15','RR/MM/DD'));
Insert into SCHRONISKO.PRACOWNICY (ID,IMIE,NAZWISKO,PENSJA,STANOWISKO,ADRES_ID,DATA_ZATRUDNIENIA) values ('9','Ewa','Wójcik','4500','Koordynator Adopcji','4',to_date('22/02/18','RR/MM/DD'));
REM INSERTING into SCHRONISKO.PRACOWNIK_ZWIERZETA
SET DEFINE OFF;
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('1','1');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('1','3');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('1','5');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('1','7');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('1','8');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('1','10');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('2','1');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('2','4');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('2','7');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('2','10');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('3','2');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('3','4');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('3','6');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('3','9');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('4','2');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('4','4');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('4','6');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('4','9');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('5','2');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('5','4');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('5','6');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('5','9');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('6','2');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('6','5');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('6','8');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('7','3');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('7','6');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('7','9');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('8','1');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('8','3');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('8','5');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('8','7');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('8','8');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('8','10');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('9','1');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('9','3');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('9','5');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('9','7');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('9','8');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('9','10');
REM INSERTING into SCHRONISKO.REJESTR_ADOPCJI
SET DEFINE OFF;
REM INSERTING into SCHRONISKO.REJESTR_DAROWIZN
SET DEFINE OFF;
REM INSERTING into SCHRONISKO.ZWIERZETA
SET DEFINE OFF;
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('1','Burek','Mieszaniec','Male','Dostêpny','1',to_date('22/01/10','RR/MM/DD'),'5','Pies');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('2','Max','Owczarek Niemiecki','Male','Dostêpny','2',to_date('21/09/15','RR/MM/DD'),'3','Pies');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('3','Luna','Mieszaniec','Female','Dostêpny','3',to_date('22/05/08','RR/MM/DD'),'4','Pies');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('4','Bella','Labrador Retriever','Female','Dostêpny','4',to_date('21/11/20','RR/MM/DD'),'6','Pies');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('5','Rocky','Mieszaniec','Male','Dostêpny','5',to_date('22/07/15','RR/MM/DD'),'2','Pies');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('6','Milo','Golden Retriever','Male','Dostêpny','6',to_date('21/12/01','RR/MM/DD'),'7','Pies');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('7','Sara','Mieszaniec','Female','Dostêpny','7',to_date('22/02/17','RR/MM/DD'),'3','Pies');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('8','Tina','Mieszaniec','Female','Dostêpny','8',to_date('22/03/22','RR/MM/DD'),'4','Pies');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('9','Duke','Mieszaniec','Male','Dostêpny','9',to_date('22/04/11','RR/MM/DD'),'5','Pies');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('10','Buddy','Mieszaniec','Male','Dostêpny','10',to_date('21/10/05','RR/MM/DD'),'6','Pies');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('11','Zara','Mieszaniec','Female','Dostêpny','2',to_date('22/06/25','RR/MM/DD'),'2','Pies');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('12','Oscar','Mieszaniec','Male','Dostêpny','3',to_date('22/07/10','RR/MM/DD'),'1','Pies');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('13','Molly','Mieszaniec','Female','Dostêpny','4',to_date('21/08/12','RR/MM/DD'),'4','Pies');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('14','Baxter','Mieszaniec','Male','Dostêpny','5',to_date('22/01/25','RR/MM/DD'),'3','Pies');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('15','Lucy','Husky','Female','Dostêpny','6',to_date('21/03/30','RR/MM/DD'),'8','Pies');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('16','Luna','Mieszaniec','Female','Dostêpny','11',to_date('22/03/15','RR/MM/DD'),'6','Kot');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('17','Oliver','Mieszaniec','Male','Dostêpny','11',to_date('22/07/09','RR/MM/DD'),'5','Kot');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('18','Simba','Mieszaniec','Male','Dostêpny','12',to_date('23/02/12','RR/MM/DD'),'3','Kot');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('19','Bella','Mieszaniec','Female','Dostêpny','12',to_date('21/06/03','RR/MM/DD'),'1','Kot');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('20','Nala','Mieszaniec','Female','Dostêpny','12',to_date('23/01/25','RR/MM/DD'),'3','Kot');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('21','Milo','Mieszaniec','Male','Dostêpny','13',to_date('21/11/07','RR/MM/DD'),'7','Kot');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('22','Chloe','Mieszaniec','Female','Dostêpny','13',to_date('22/02/17','RR/MM/DD'),'5','Kot');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('23','Max','Mieszaniec','Male','Dostêpny','13',to_date('20/12/22','RR/MM/DD'),'7','Kot');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('24','Whiskers','Mieszaniec','Female','Dostêpny','13',to_date('23/06/15','RR/MM/DD'),'2','Kot');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('25','Zara','Mieszaniec','Female','Dostêpny','13',to_date('21/08/30','RR/MM/DD'),'3','Kot');
--------------------------------------------------------
--  DDL for Index SYS_C008274
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008274" ON "SCHRONISKO"."KOJCE" ("KOJEC_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008277
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008277" ON "SCHRONISKO"."ADRESY" ("ID_ADRESU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008279
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008279" ON "SCHRONISKO"."DARCZYNCY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008280
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008280" ON "SCHRONISKO"."DARCZYNCY" ("NAZWA_UZYTKOWNIKA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008281
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008281" ON "SCHRONISKO"."DARCZYNCY" ("MAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008284
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008284" ON "SCHRONISKO"."REJESTR_DAROWIZN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008288
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008288" ON "SCHRONISKO"."OSOBY_ADOPTUJACE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008292
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008292" ON "SCHRONISKO"."PRACOWNICY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008294
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008294" ON "SCHRONISKO"."ZWIERZETA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008298
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008298" ON "SCHRONISKO"."REJESTR_ADOPCJI" ("ID_ADOPCJI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008302
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008302" ON "SCHRONISKO"."PRACOWNIK_ZWIERZETA" ("PRACOWNIK_ID", "ZWIERZE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008277
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008277" ON "SCHRONISKO"."ADRESY" ("ID_ADRESU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008279
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008279" ON "SCHRONISKO"."DARCZYNCY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008280
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008280" ON "SCHRONISKO"."DARCZYNCY" ("NAZWA_UZYTKOWNIKA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008281
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008281" ON "SCHRONISKO"."DARCZYNCY" ("MAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008274
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008274" ON "SCHRONISKO"."KOJCE" ("KOJEC_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008288
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008288" ON "SCHRONISKO"."OSOBY_ADOPTUJACE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008292
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008292" ON "SCHRONISKO"."PRACOWNICY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008302
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008302" ON "SCHRONISKO"."PRACOWNIK_ZWIERZETA" ("PRACOWNIK_ID", "ZWIERZE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008298
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008298" ON "SCHRONISKO"."REJESTR_ADOPCJI" ("ID_ADOPCJI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008284
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008284" ON "SCHRONISKO"."REJESTR_DAROWIZN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008294
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008294" ON "SCHRONISKO"."ZWIERZETA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger PRACOWNICY_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SCHRONISKO"."PRACOWNICY_TRIGGER" 
BEFORE INSERT ON pracownicy
FOR EACH ROW
BEGIN
    :new.ID := pracownicy_seq.NEXTVAL;
END;

/
ALTER TRIGGER "SCHRONISKO"."PRACOWNICY_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PRACOWNICY_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SCHRONISKO"."PRACOWNICY_TRIGGER" 
BEFORE INSERT ON pracownicy
FOR EACH ROW
BEGIN
    :new.ID := pracownicy_seq.NEXTVAL;
END;

/
ALTER TRIGGER "SCHRONISKO"."PRACOWNICY_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Procedure DODAJ_ADRES
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHRONISKO"."DODAJ_ADRES" (
    p_miasto VARCHAR2,
    p_kod_pocztowy VARCHAR2,
    p_ulica VARCHAR2,
    p_numer_domu VARCHAR2,
    p_numer_mieszkania VARCHAR2
) AS
BEGIN
    INSERT INTO Adresy (ID_ADRESU, MIASTO, KOD_POCZTOWY, ULICA, NUMER_DOMU, NUMER_MIESZKANIA)
    VALUES (Adresy_seq.NEXTVAL, p_miasto, p_kod_pocztowy, p_ulica, p_numer_domu, p_numer_mieszkania);
    COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Procedure DODAJ_PRACOWNIKA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHRONISKO"."DODAJ_PRACOWNIKA" (
    p_imie VARCHAR2,
    p_nazwisko VARCHAR2,
    p_pensja NUMBER,
    p_stanowisko VARCHAR2,
    p_adres_id NUMBER,
    p_data_zatrudnienia DATE
) AS
BEGIN
    INSERT INTO Pracownicy (ID, IMIE, NAZWISKO, PENSJA, STANOWISKO, ADRES_ID, DATA_ZATRUDNIENIA)
    VALUES (Pracownicy_seq.NEXTVAL, p_imie, p_nazwisko, p_pensja, p_stanowisko, p_adres_id, p_data_zatrudnienia);
    COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Procedure EDYTUJ_ADRES
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHRONISKO"."EDYTUJ_ADRES" (
    p_id_adresu NUMBER,
    p_miasto VARCHAR2,
    p_kod_pocztowy VARCHAR2,
    p_ulica VARCHAR2,
    p_numer_domu VARCHAR2,
    p_numer_mieszkania VARCHAR2
) AS
BEGIN
    UPDATE Adresy
    SET MIASTO = p_miasto,
        KOD_POCZTOWY = p_kod_pocztowy,
        ULICA = p_ulica,
        NUMER_DOMU = p_numer_domu,
        NUMER_MIESZKANIA = p_numer_mieszkania
    WHERE ID_ADRESU = p_id_adresu;
    COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Procedure EDYTUJ_PRACOWNIKA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHRONISKO"."EDYTUJ_PRACOWNIKA" (
    p_id NUMBER,
    p_imie VARCHAR2,
    p_nazwisko VARCHAR2,
    p_pensja NUMBER,
    p_stanowisko VARCHAR2,
    p_adres_id NUMBER,
    p_data_zatrudnienia DATE
) AS
BEGIN
    UPDATE Pracownicy
    SET IMIE = p_imie,
        NAZWISKO = p_nazwisko,
        PENSJA = p_pensja,
        STANOWISKO = p_stanowisko,
        ADRES_ID = p_adres_id,
        DATA_ZATRUDNIENIA = p_data_zatrudnienia
    WHERE ID = p_id;
    COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Procedure USUN_ADRES
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHRONISKO"."USUN_ADRES" (
    p_id NUMBER
) AS
BEGIN
    DELETE FROM Adresy WHERE ID_ADRESU = p_id;
    COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Procedure USUN_PRACOWNIKA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHRONISKO"."USUN_PRACOWNIKA" (
    p_id NUMBER
) AS
BEGIN
    DELETE FROM Pracownicy WHERE ID = p_id;
    COMMIT;
END;

/
--------------------------------------------------------
--  Constraints for Table ADRESY
--------------------------------------------------------

  ALTER TABLE "SCHRONISKO"."ADRESY" MODIFY ("MIASTO" NOT NULL ENABLE);
  ALTER TABLE "SCHRONISKO"."ADRESY" MODIFY ("KOD_POCZTOWY" NOT NULL ENABLE);
  ALTER TABLE "SCHRONISKO"."ADRESY" ADD PRIMARY KEY ("ID_ADRESU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DARCZYNCY
--------------------------------------------------------

  ALTER TABLE "SCHRONISKO"."DARCZYNCY" MODIFY ("NAZWA_UZYTKOWNIKA" NOT NULL ENABLE);
  ALTER TABLE "SCHRONISKO"."DARCZYNCY" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCHRONISKO"."DARCZYNCY" ADD UNIQUE ("NAZWA_UZYTKOWNIKA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCHRONISKO"."DARCZYNCY" ADD UNIQUE ("MAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KOJCE
--------------------------------------------------------

  ALTER TABLE "SCHRONISKO"."KOJCE" ADD PRIMARY KEY ("KOJEC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table OSOBY_ADOPTUJACE
--------------------------------------------------------

  ALTER TABLE "SCHRONISKO"."OSOBY_ADOPTUJACE" MODIFY ("IMIE" NOT NULL ENABLE);
  ALTER TABLE "SCHRONISKO"."OSOBY_ADOPTUJACE" MODIFY ("NAZWISKO" NOT NULL ENABLE);
  ALTER TABLE "SCHRONISKO"."OSOBY_ADOPTUJACE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRACOWNICY
--------------------------------------------------------

  ALTER TABLE "SCHRONISKO"."PRACOWNICY" MODIFY ("IMIE" NOT NULL ENABLE);
  ALTER TABLE "SCHRONISKO"."PRACOWNICY" MODIFY ("NAZWISKO" NOT NULL ENABLE);
  ALTER TABLE "SCHRONISKO"."PRACOWNICY" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRACOWNIK_ZWIERZETA
--------------------------------------------------------

  ALTER TABLE "SCHRONISKO"."PRACOWNIK_ZWIERZETA" ADD PRIMARY KEY ("PRACOWNIK_ID", "ZWIERZE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REJESTR_ADOPCJI
--------------------------------------------------------

  ALTER TABLE "SCHRONISKO"."REJESTR_ADOPCJI" MODIFY ("DATA_ADOPCJI" NOT NULL ENABLE);
  ALTER TABLE "SCHRONISKO"."REJESTR_ADOPCJI" ADD PRIMARY KEY ("ID_ADOPCJI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REJESTR_DAROWIZN
--------------------------------------------------------

  ALTER TABLE "SCHRONISKO"."REJESTR_DAROWIZN" MODIFY ("KWOTA" NOT NULL ENABLE);
  ALTER TABLE "SCHRONISKO"."REJESTR_DAROWIZN" MODIFY ("DATA" NOT NULL ENABLE);
  ALTER TABLE "SCHRONISKO"."REJESTR_DAROWIZN" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ZWIERZETA
--------------------------------------------------------

  ALTER TABLE "SCHRONISKO"."ZWIERZETA" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OSOBY_ADOPTUJACE
--------------------------------------------------------

  ALTER TABLE "SCHRONISKO"."OSOBY_ADOPTUJACE" ADD FOREIGN KEY ("ADRES_ID")
	  REFERENCES "SCHRONISKO"."ADRESY" ("ID_ADRESU") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRACOWNICY
--------------------------------------------------------

  ALTER TABLE "SCHRONISKO"."PRACOWNICY" ADD FOREIGN KEY ("ADRES_ID")
	  REFERENCES "SCHRONISKO"."ADRESY" ("ID_ADRESU") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRACOWNIK_ZWIERZETA
--------------------------------------------------------

  ALTER TABLE "SCHRONISKO"."PRACOWNIK_ZWIERZETA" ADD FOREIGN KEY ("PRACOWNIK_ID")
	  REFERENCES "SCHRONISKO"."PRACOWNICY" ("ID") ENABLE;
  ALTER TABLE "SCHRONISKO"."PRACOWNIK_ZWIERZETA" ADD FOREIGN KEY ("ZWIERZE_ID")
	  REFERENCES "SCHRONISKO"."ZWIERZETA" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REJESTR_ADOPCJI
--------------------------------------------------------

  ALTER TABLE "SCHRONISKO"."REJESTR_ADOPCJI" ADD FOREIGN KEY ("OSOBA_ADOPTUJACA")
	  REFERENCES "SCHRONISKO"."OSOBY_ADOPTUJACE" ("ID") ENABLE;
  ALTER TABLE "SCHRONISKO"."REJESTR_ADOPCJI" ADD FOREIGN KEY ("ZWIERZE_ID")
	  REFERENCES "SCHRONISKO"."ZWIERZETA" ("ID") ENABLE;
  ALTER TABLE "SCHRONISKO"."REJESTR_ADOPCJI" ADD FOREIGN KEY ("PRACOWNIK_ID")
	  REFERENCES "SCHRONISKO"."PRACOWNICY" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REJESTR_DAROWIZN
--------------------------------------------------------

  ALTER TABLE "SCHRONISKO"."REJESTR_DAROWIZN" ADD FOREIGN KEY ("DARCZYNCA_ID")
	  REFERENCES "SCHRONISKO"."DARCZYNCY" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ZWIERZETA
--------------------------------------------------------

  ALTER TABLE "SCHRONISKO"."ZWIERZETA" ADD FOREIGN KEY ("KOJEC_ID")
	  REFERENCES "SCHRONISKO"."KOJCE" ("KOJEC_ID") ENABLE;
