--------------------------------------------------------
--  File created - wtorek-stycznia-21-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ADRESY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SCHRONISKO"."ADRESY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 51 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence DARCZYNCY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SCHRONISKO"."DARCZYNCY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 74 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence DAROWIZNY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SCHRONISKO"."DAROWIZNY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 35 CACHE 25 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence DEPT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SCHRONISKO"."DEPT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence DEPT_SEQ2
--------------------------------------------------------

   CREATE SEQUENCE  "SCHRONISKO"."DEPT_SEQ2"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence KOJCE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SCHRONISKO"."KOJCE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 35 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PRACOWNICY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SCHRONISKO"."PRACOWNICY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 51 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence REJESTR_ADOPCJI_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SCHRONISKO"."REJESTR_ADOPCJI_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 5 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ADOPCJE_ID
--------------------------------------------------------

   CREATE SEQUENCE  "SCHRONISKO"."SEQ_ADOPCJE_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 23 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence ZWIERZETA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SCHRONISKO"."ZWIERZETA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 34 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table ADRESY
--------------------------------------------------------

  CREATE TABLE "SCHRONISKO"."ADRESY" 
   (	"ID_ADRESU" NUMBER, 
	"MIASTO" VARCHAR2(50 BYTE), 
	"KOD_POCZTOWY" VARCHAR2(10 BYTE), 
	"ULICA" VARCHAR2(100 BYTE), 
	"NUMER_DOMU" VARCHAR2(10 BYTE), 
	"NUMER_MIESZKANIA" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DARCZYNCY
--------------------------------------------------------

  CREATE TABLE "SCHRONISKO"."DARCZYNCY" 
   (	"ID" NUMBER, 
	"NAZWA_UZYTKOWNIKA" VARCHAR2(50 BYTE), 
	"IMIE" VARCHAR2(50 BYTE), 
	"NAZWISKO" VARCHAR2(50 BYTE), 
	"MAIL" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KOJCE
--------------------------------------------------------

  CREATE TABLE "SCHRONISKO"."KOJCE" 
   (	"KOJEC_ID" NUMBER, 
	"WIELKOSC" VARCHAR2(20 BYTE), 
	"NUMER" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRACOWNICY
--------------------------------------------------------

  CREATE TABLE "SCHRONISKO"."PRACOWNICY" 
   (	"ID" NUMBER, 
	"IMIE" VARCHAR2(50 BYTE), 
	"NAZWISKO" VARCHAR2(50 BYTE), 
	"PENSJA" NUMBER(10,2), 
	"STANOWISKO" VARCHAR2(100 BYTE), 
	"ADRES_ID" NUMBER, 
	"DATA_ZATRUDNIENIA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRACOWNIK_ZWIERZETA
--------------------------------------------------------

  CREATE TABLE "SCHRONISKO"."PRACOWNIK_ZWIERZETA" 
   (	"PRACOWNIK_ID" NUMBER, 
	"ZWIERZE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REJESTR_ADOPCJI
--------------------------------------------------------

  CREATE TABLE "SCHRONISKO"."REJESTR_ADOPCJI" 
   (	"ID_ADOPCJI" NUMBER, 
	"DATA_ADOPCJI" DATE, 
	"ZWIERZE_ID" NUMBER, 
	"PRACOWNIK_ID" NUMBER, 
	"IMIE" VARCHAR2(100 BYTE), 
	"NAZWISKO" VARCHAR2(100 BYTE), 
	"ADRES_ID" NUMBER, 
	"NUMER_TELEFONU" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REJESTR_DAROWIZN
--------------------------------------------------------

  CREATE TABLE "SCHRONISKO"."REJESTR_DAROWIZN" 
   (	"ID" NUMBER, 
	"DARCZYNCA_ID" NUMBER, 
	"KWOTA" NUMBER(10,2), 
	"DATA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ZWIERZETA
--------------------------------------------------------

  CREATE TABLE "SCHRONISKO"."ZWIERZETA" 
   (	"ID" NUMBER, 
	"IMIE" VARCHAR2(50 BYTE), 
	"RASA" VARCHAR2(50 BYTE), 
	"PLEC" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(50 BYTE), 
	"KOJEC_ID" NUMBER, 
	"DATA_PRZYJECIA" DATE, 
	"WIEK" NUMBER, 
	"TYP" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SCHRONISKO.ADRESY
SET DEFINE OFF;
Insert into SCHRONISKO.ADRESY (ID_ADRESU,MIASTO,KOD_POCZTOWY,ULICA,NUMER_DOMU,NUMER_MIESZKANIA) values ('1','Warszawa','00-001','Marszałkowska','12','1');
Insert into SCHRONISKO.ADRESY (ID_ADRESU,MIASTO,KOD_POCZTOWY,ULICA,NUMER_DOMU,NUMER_MIESZKANIA) values ('2','Kraków','30-001','Floriańska','25','2');
Insert into SCHRONISKO.ADRESY (ID_ADRESU,MIASTO,KOD_POCZTOWY,ULICA,NUMER_DOMU,NUMER_MIESZKANIA) values ('3','Poznań','60-001','Wielka','15','3');
Insert into SCHRONISKO.ADRESY (ID_ADRESU,MIASTO,KOD_POCZTOWY,ULICA,NUMER_DOMU,NUMER_MIESZKANIA) values ('4','Wrocław','50-001','Świdnicka','8','4');
Insert into SCHRONISKO.ADRESY (ID_ADRESU,MIASTO,KOD_POCZTOWY,ULICA,NUMER_DOMU,NUMER_MIESZKANIA) values ('5','Gdańsk','80-001','Długa','19','5');
Insert into SCHRONISKO.ADRESY (ID_ADRESU,MIASTO,KOD_POCZTOWY,ULICA,NUMER_DOMU,NUMER_MIESZKANIA) values ('6','Szczecin','70-001','Pilsudskiego','3','6');
Insert into SCHRONISKO.ADRESY (ID_ADRESU,MIASTO,KOD_POCZTOWY,ULICA,NUMER_DOMU,NUMER_MIESZKANIA) values ('8','Łódź','90-001','Piotrkowska','11','8');
REM INSERTING into SCHRONISKO.DARCZYNCY
SET DEFINE OFF;
Insert into SCHRONISKO.DARCZYNCY (ID,NAZWA_UZYTKOWNIKA,IMIE,NAZWISKO,MAIL) values ('80','oskar_boruwa','Oskar','Borówka','o.boruwa@example.com');
Insert into SCHRONISKO.DARCZYNCY (ID,NAZWA_UZYTKOWNIKA,IMIE,NAZWISKO,MAIL) values ('64','jan_kowalski','Jan','Kowalski','jan.kowalski@example.com');
Insert into SCHRONISKO.DARCZYNCY (ID,NAZWA_UZYTKOWNIKA,IMIE,NAZWISKO,MAIL) values ('65','anna_nowak','Anna','Nowak','anna.nowak@example.com');
Insert into SCHRONISKO.DARCZYNCY (ID,NAZWA_UZYTKOWNIKA,IMIE,NAZWISKO,MAIL) values ('69','ewa_kaczmarek','Ewa','Kaczmarek','ewa.kaczmarek@example.com');
Insert into SCHRONISKO.DARCZYNCY (ID,NAZWA_UZYTKOWNIKA,IMIE,NAZWISKO,MAIL) values ('66','piotr_wisniewski','Piotr','Wisniewski','piotr.wisniewski@example.com');
Insert into SCHRONISKO.DARCZYNCY (ID,NAZWA_UZYTKOWNIKA,IMIE,NAZWISKO,MAIL) values ('67','katarzyna_kaminska','Katarzyna','Kaminska','katarzyna.kaminska@example.com');
Insert into SCHRONISKO.DARCZYNCY (ID,NAZWA_UZYTKOWNIKA,IMIE,NAZWISKO,MAIL) values ('68','michal_wojcik','Michal','Wojcik','michal.wojcik@example.com');
Insert into SCHRONISKO.DARCZYNCY (ID,NAZWA_UZYTKOWNIKA,IMIE,NAZWISKO,MAIL) values ('70','tomasz_lewandowski','Tomasz','Lewandowski','tomasz.lewandowski@example.com');
Insert into SCHRONISKO.DARCZYNCY (ID,NAZWA_UZYTKOWNIKA,IMIE,NAZWISKO,MAIL) values ('71','joanna_zielinska','Joanna','Zielinska','joanna.zielinska@example.com');
Insert into SCHRONISKO.DARCZYNCY (ID,NAZWA_UZYTKOWNIKA,IMIE,NAZWISKO,MAIL) values ('72','robert_szymanski','Robert','Szymanski','robert.szymanski@example.com');
Insert into SCHRONISKO.DARCZYNCY (ID,NAZWA_UZYTKOWNIKA,IMIE,NAZWISKO,MAIL) values ('73','maria_wozniak','Maria','Wozniak','maria.wozniak@example.com');
REM INSERTING into SCHRONISKO.KOJCE
SET DEFINE OFF;
Insert into SCHRONISKO.KOJCE (KOJEC_ID,WIELKOSC,NUMER) values ('1','Mały','K01DOG');
Insert into SCHRONISKO.KOJCE (KOJEC_ID,WIELKOSC,NUMER) values ('2','Średni','K02DOG');
Insert into SCHRONISKO.KOJCE (KOJEC_ID,WIELKOSC,NUMER) values ('3','Duży','K03DOG');
Insert into SCHRONISKO.KOJCE (KOJEC_ID,WIELKOSC,NUMER) values ('4','Mały','K04DOG');
Insert into SCHRONISKO.KOJCE (KOJEC_ID,WIELKOSC,NUMER) values ('5','Średni','K05DOG');
Insert into SCHRONISKO.KOJCE (KOJEC_ID,WIELKOSC,NUMER) values ('6','Duży','K06DOG');
Insert into SCHRONISKO.KOJCE (KOJEC_ID,WIELKOSC,NUMER) values ('7','Mały','K07DOG');
Insert into SCHRONISKO.KOJCE (KOJEC_ID,WIELKOSC,NUMER) values ('8','Średni','K08DOG');
Insert into SCHRONISKO.KOJCE (KOJEC_ID,WIELKOSC,NUMER) values ('9','Duży','K09DOG');
Insert into SCHRONISKO.KOJCE (KOJEC_ID,WIELKOSC,NUMER) values ('10','Średni','K10DOG');
Insert into SCHRONISKO.KOJCE (KOJEC_ID,WIELKOSC,NUMER) values ('11','Mały','K11CAT');
Insert into SCHRONISKO.KOJCE (KOJEC_ID,WIELKOSC,NUMER) values ('12','Średni','K12CAT');
Insert into SCHRONISKO.KOJCE (KOJEC_ID,WIELKOSC,NUMER) values ('13','Duży','K13CAT');
REM INSERTING into SCHRONISKO.PRACOWNICY
SET DEFINE OFF;
Insert into SCHRONISKO.PRACOWNICY (ID,IMIE,NAZWISKO,PENSJA,STANOWISKO,ADRES_ID,DATA_ZATRUDNIENIA) values ('31','Michal','Wata','5500','Koordynator Adopcji','3',to_date('24/12/02','RR/MM/DD'));
Insert into SCHRONISKO.PRACOWNICY (ID,IMIE,NAZWISKO,PENSJA,STANOWISKO,ADRES_ID,DATA_ZATRUDNIENIA) values ('1','Anna','Kowalska','4500','Weterynarz','1',to_date('23/05/10','RR/MM/DD'));
Insert into SCHRONISKO.PRACOWNICY (ID,IMIE,NAZWISKO,PENSJA,STANOWISKO,ADRES_ID,DATA_ZATRUDNIENIA) values ('2','Piotr','Nowak','5000','Weterynarz','2',to_date('22/11/23','RR/MM/DD'));
Insert into SCHRONISKO.PRACOWNICY (ID,IMIE,NAZWISKO,PENSJA,STANOWISKO,ADRES_ID,DATA_ZATRUDNIENIA) values ('3','Ewa','Zielińska','2500','Sprzatacz','3',to_date('24/01/01','RR/MM/DD'));
Insert into SCHRONISKO.PRACOWNICY (ID,IMIE,NAZWISKO,PENSJA,STANOWISKO,ADRES_ID,DATA_ZATRUDNIENIA) values ('4','Krzysztof','Wójcik','2600','Sprzatacz','4',to_date('23/09/10','RR/MM/DD'));
Insert into SCHRONISKO.PRACOWNICY (ID,IMIE,NAZWISKO,PENSJA,STANOWISKO,ADRES_ID,DATA_ZATRUDNIENIA) values ('5','Monika','Lewandowska','3000','Opiekun Zwierzat','5',to_date('24/02/15','RR/MM/DD'));
Insert into SCHRONISKO.PRACOWNICY (ID,IMIE,NAZWISKO,PENSJA,STANOWISKO,ADRES_ID,DATA_ZATRUDNIENIA) values ('6','Tomasz','Szymański','3200','Opiekun Zwierzat','6',to_date('23/06/12','RR/MM/DD'));
Insert into SCHRONISKO.PRACOWNICY (ID,IMIE,NAZWISKO,PENSJA,STANOWISKO,ADRES_ID,DATA_ZATRUDNIENIA) values ('7','Kacper','Szaleniec','5900','Koordynator Adopcji','3',to_date('24/12/02','RR/MM/DD'));
Insert into SCHRONISKO.PRACOWNICY (ID,IMIE,NAZWISKO,PENSJA,STANOWISKO,ADRES_ID,DATA_ZATRUDNIENIA) values ('8','Marek','Jankowski','6000','Koordynator Adopcji','8',to_date('22/08/05','RR/MM/DD'));
REM INSERTING into SCHRONISKO.PRACOWNIK_ZWIERZETA
SET DEFINE OFF;
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('1','1');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('1','3');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('1','5');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('1','7');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('1','9');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('1','11');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('1','13');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('2','2');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('2','4');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('2','6');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('2','8');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('2','10');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('2','12');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('2','14');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('2','34');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('3','1');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('3','3');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('3','5');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('3','7');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('3','9');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('3','11');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('3','13');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('3','34');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('4','2');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('4','4');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('4','6');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('4','8');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('4','10');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('4','12');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('4','14');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('5','1');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('5','3');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('5','5');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('5','7');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('5','9');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('5','11');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('5','13');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('5','34');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('6','2');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('6','4');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('6','6');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('6','8');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('6','10');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('6','12');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('6','14');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('7','3');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('7','5');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('7','7');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('7','9');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('7','11');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('7','13');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('8','2');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('8','4');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('8','6');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('8','8');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('8','10');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('8','12');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('8','14');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('8','34');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('31','1');
REM INSERTING into SCHRONISKO.REJESTR_ADOPCJI
SET DEFINE OFF;
Insert into SCHRONISKO.REJESTR_ADOPCJI (ID_ADOPCJI,DATA_ADOPCJI,ZWIERZE_ID,PRACOWNIK_ID,IMIE,NAZWISKO,ADRES_ID,NUMER_TELEFONU) values ('19',to_date('25/01/07','RR/MM/DD'),'6','8','Zbigniew','Jankowski','3','33344455');
Insert into SCHRONISKO.REJESTR_ADOPCJI (ID_ADOPCJI,DATA_ADOPCJI,ZWIERZE_ID,PRACOWNIK_ID,IMIE,NAZWISKO,ADRES_ID,NUMER_TELEFONU) values ('20',to_date('25/01/07','RR/MM/DD'),'9','8','asdasd','asdasdas','4','33344455');
Insert into SCHRONISKO.REJESTR_ADOPCJI (ID_ADOPCJI,DATA_ADOPCJI,ZWIERZE_ID,PRACOWNIK_ID,IMIE,NAZWISKO,ADRES_ID,NUMER_TELEFONU) values ('17',to_date('24/11/12','RR/MM/DD'),'4','8','Katarzyna','Sigmoza','5','111222333');
REM INSERTING into SCHRONISKO.REJESTR_DAROWIZN
SET DEFINE OFF;
Insert into SCHRONISKO.REJESTR_DAROWIZN (ID,DARCZYNCA_ID,KWOTA,DATA) values ('81','80','10000',to_date('25/01/16','RR/MM/DD'));
Insert into SCHRONISKO.REJESTR_DAROWIZN (ID,DARCZYNCA_ID,KWOTA,DATA) values ('32','66','1000',to_date('25/01/08','RR/MM/DD'));
Insert into SCHRONISKO.REJESTR_DAROWIZN (ID,DARCZYNCA_ID,KWOTA,DATA) values ('33','71','67',to_date('25/01/06','RR/MM/DD'));
Insert into SCHRONISKO.REJESTR_DAROWIZN (ID,DARCZYNCA_ID,KWOTA,DATA) values ('34','69','10',to_date('25/01/10','RR/MM/DD'));
Insert into SCHRONISKO.REJESTR_DAROWIZN (ID,DARCZYNCA_ID,KWOTA,DATA) values ('31',null,'555',to_date('25/01/09','RR/MM/DD'));
REM INSERTING into SCHRONISKO.ZWIERZETA
SET DEFINE OFF;
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('1','Ares','Mieszaniec','Male','Dostepny','1',to_date('24/07/21','RR/MM/DD'),'3','Pies');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('2','Rex','Owczarek niemiecki','Male','Dostępny','2',to_date('24/10/15','RR/MM/DD'),'5','Pies');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('3','Azor','Mieszaniec','Male','Dostepny','3',to_date('24/07/01','RR/MM/DD'),'4','Pies');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('4','Luna','Labrador','Female','Dostepny','4',to_date('24/09/05','RR/MM/DD'),'2','Pies');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('5','Max','Mieszaniec','Male','Dostepny','5',to_date('22/09/16','RR/MM/DD'),'1','Pies');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('6','Bella','Mieszaniec','Female','Adoptowany','6',to_date('24/10/29','RR/MM/DD'),'6','Pies');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('7','Charlie','Beagle','Male','Dostepny','7',to_date('24/08/10','RR/MM/DD'),'3','Pies');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('8','Rocky','Mieszaniec','Male','Dostepny','8',to_date('24/02/20','RR/MM/DD'),'4','Pies');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('9','Daisy','Collie','Female','Adoptowany','9',to_date('24/06/10','RR/MM/DD'),'2','Pies');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('10','Shadow','Mieszaniec','Male','Dostepny','10',to_date('24/10/02','RR/MM/DD'),'7','Pies');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('11','Mimi','Mieszańec','Female','Dostepny','11',to_date('24/10/01','RR/MM/DD'),'2','Kot');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('12','Tina','Mieszańec','Female','Dostepny','12',to_date('24/09/15','RR/MM/DD'),'3','Kot');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('13','Tommy','Mieszańec','Male','Dostepny','13',to_date('24/07/20','RR/MM/DD'),'4','Kot');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('14','Lizak','Mieszaniec','Male','Dostepny','9',to_date('24/11/06','RR/MM/DD'),'13','Pies');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('34','Brutus','Mieszaniec','Male','Dostepny','7',to_date('24/12/31','RR/MM/DD'),'11','Pies');
--------------------------------------------------------
--  DDL for Index SYS_C008274
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008274" ON "SCHRONISKO"."KOJCE" ("KOJEC_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008277
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008277" ON "SCHRONISKO"."ADRESY" ("ID_ADRESU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008279
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008279" ON "SCHRONISKO"."DARCZYNCY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008280
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008280" ON "SCHRONISKO"."DARCZYNCY" ("NAZWA_UZYTKOWNIKA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008281
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008281" ON "SCHRONISKO"."DARCZYNCY" ("MAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008284
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008284" ON "SCHRONISKO"."REJESTR_DAROWIZN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008292
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008292" ON "SCHRONISKO"."PRACOWNICY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008294
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008294" ON "SCHRONISKO"."ZWIERZETA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008298
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008298" ON "SCHRONISKO"."REJESTR_ADOPCJI" ("ID_ADOPCJI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008302
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008302" ON "SCHRONISKO"."PRACOWNIK_ZWIERZETA" ("PRACOWNIK_ID", "ZWIERZE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008277
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008277" ON "SCHRONISKO"."ADRESY" ("ID_ADRESU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008279
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008279" ON "SCHRONISKO"."DARCZYNCY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008280
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008280" ON "SCHRONISKO"."DARCZYNCY" ("NAZWA_UZYTKOWNIKA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008281
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008281" ON "SCHRONISKO"."DARCZYNCY" ("MAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008274
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008274" ON "SCHRONISKO"."KOJCE" ("KOJEC_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008292
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008292" ON "SCHRONISKO"."PRACOWNICY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008302
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008302" ON "SCHRONISKO"."PRACOWNIK_ZWIERZETA" ("PRACOWNIK_ID", "ZWIERZE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008298
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008298" ON "SCHRONISKO"."REJESTR_ADOPCJI" ("ID_ADOPCJI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008284
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008284" ON "SCHRONISKO"."REJESTR_DAROWIZN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008294
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008294" ON "SCHRONISKO"."ZWIERZETA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Procedure DODAJ_ADOPCJE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHRONISKO"."DODAJ_ADOPCJE" (
    id_zwierzecia IN NUMBER,
    id_pracownika IN NUMBER,
    id_adresu IN NUMBER,
    data_adopcji IN DATE,
    imie IN VARCHAR2,
    nazwisko IN VARCHAR2,
    numer_telefonu IN VARCHAR2
) AS
BEGIN
    -- Wstawianie danych do tabeli REJESTR_ADOPCJI
    INSERT INTO REJESTR_ADOPCJI (
        ID_ADOPCJI,
        ZWIERZE_ID,
        PRACOWNIK_ID,
        ADRES_ID,
        DATA_ADOPCJI,
        IMIE,
        NAZWISKO,
        NUMER_TELEFONU
    ) VALUES (
        seq_adopcje_id.NEXTVAL, -- Automatyczne przypisywanie ID
        id_zwierzecia,
        id_pracownika,
        id_adresu,
        data_adopcji,
        imie,
        nazwisko,
        numer_telefonu
    );

    -- Zatwierdzenie transakcji
    COMMIT;

END;






/
--------------------------------------------------------
--  DDL for Procedure DODAJ_ADRES
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHRONISKO"."DODAJ_ADRES" (
    p_miasto VARCHAR2,
    p_kod_pocztowy VARCHAR2,
    p_ulica VARCHAR2,
    p_numer_domu VARCHAR2,
    p_numer_mieszkania VARCHAR2
) AS
BEGIN
    INSERT INTO Adresy (
        ID_ADRESU, 
        MIASTO, 
        KOD_POCZTOWY, 
        ULICA, 
        NUMER_DOMU, 
        NUMER_MIESZKANIA
    )
    VALUES (
        Adresy_seq.NEXTVAL, 
        p_miasto, 
        p_kod_pocztowy, 
        p_ulica, 
        CASE WHEN p_numer_domu IS NULL OR p_numer_domu = '' THEN NULL ELSE p_numer_domu END, 
        CASE WHEN p_numer_mieszkania IS NULL OR p_numer_mieszkania = '' THEN NULL ELSE p_numer_mieszkania END
    );
    COMMIT;
END;






/
--------------------------------------------------------
--  DDL for Procedure DODAJ_DARCZYNCE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHRONISKO"."DODAJ_DARCZYNCE" (
    p_nazwa_uzytkownika     VARCHAR2,
    p_imie                  VARCHAR2,
    p_nazwisko              VARCHAR2,
    p_mail                  VARCHAR2
) AS 
BEGIN
    INSERT INTO DARCZYNCY (
        ID, NAZWA_UZYTKOWNIKA, IMIE, NAZWISKO, MAIL
    )
    VALUES (
        DARCZYNCY_SEQ.NEXTVAL, p_nazwa_uzytkownika, P_imie, p_nazwisko, p_mail
    );
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001, 'B��d w procedurze DODAJ_DARCZYNCE: ' || SQLERRM);
END DODAJ_DARCZYNCE;





/
--------------------------------------------------------
--  DDL for Procedure DODAJ_DAROWIZNE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHRONISKO"."DODAJ_DAROWIZNE" (
    p_darczynca_id IN NUMBER,
    p_kwota IN NUMBER,
    p_data IN DATE
) AS
BEGIN
    -- Wstawienie nowego rekordu do tabeli REJESTR_DAROWIZN
    INSERT INTO SCHRONISKO.REJESTR_DAROWIZN (ID, DARCZYNCA_ID, KWOTA, DATA)
    VALUES (DAROWIZNY_SEQ.NEXTVAL, p_darczynca_id, p_kwota, p_data);

    -- Zatwierdzenie transakcji
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        -- Obs�uga b��d�w
        ROLLBACK;
        RAISE;
END;





/
--------------------------------------------------------
--  DDL for Procedure DODAJ_KOJEC
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHRONISKO"."DODAJ_KOJEC" (
    p_NUMER IN VARCHAR2,
    p_WIELKOSC IN VARCHAR2
) AS
BEGIN
    INSERT INTO KOJCE (KOJEC_ID, NUMER, WIELKOSC)
    VALUES (KOJCE_SEQ.NEXTVAL, p_NUMER, p_WIELKOSC);
END;




/
--------------------------------------------------------
--  DDL for Procedure DODAJ_PRACOWNIKA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHRONISKO"."DODAJ_PRACOWNIKA" (
    p_imie VARCHAR2,
    p_nazwisko VARCHAR2,
    p_pensja NUMBER,
    p_stanowisko VARCHAR2,
    p_adres_id NUMBER,
    p_data_zatrudnienia DATE
) AS
BEGIN
    INSERT INTO Pracownicy (ID, IMIE, NAZWISKO, PENSJA, STANOWISKO, ADRES_ID, DATA_ZATRUDNIENIA)
    VALUES (Pracownicy_seq.NEXTVAL, p_imie, p_nazwisko, p_pensja, p_stanowisko, p_adres_id, p_data_zatrudnienia);
    COMMIT;
END;






/
--------------------------------------------------------
--  DDL for Procedure DODAJ_ZWIERZE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHRONISKO"."DODAJ_ZWIERZE" (
    p_imie          VARCHAR2,
    p_rasa           VARCHAR2,
    p_plec           VARCHAR2,
    p_status         VARCHAR2,
    p_kojec_id       NUMBER,
    p_data_przyjecia DATE,
    p_wiek           NUMBER,
    p_typ            VARCHAR2
) AS
BEGIN
    INSERT INTO ZWIERZETA (
        ID, IMIE, RASA, PLEC, STATUS, KOJEC_ID, DATA_PRZYJECIA, WIEK, TYP
    ) 
    VALUES (
        ZWIERZETA_SEQ.NEXTVAL, p_imie, p_rasa, p_plec, p_status, p_kojec_id, p_data_przyjecia, p_wiek, p_typ
    );
    COMMIT;
END;






/
--------------------------------------------------------
--  DDL for Procedure EDYTUJ_ADRES
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHRONISKO"."EDYTUJ_ADRES" (
    p_id_adresu NUMBER,
    p_miasto VARCHAR2,
    p_kod_pocztowy VARCHAR2,
    p_ulica VARCHAR2,
    p_numer_domu VARCHAR2,
    p_numer_mieszkania VARCHAR2
) AS
BEGIN
    UPDATE Adresy
    SET MIASTO = p_miasto,
        KOD_POCZTOWY = p_kod_pocztowy,
        ULICA = p_ulica,
        NUMER_DOMU = p_numer_domu,
        NUMER_MIESZKANIA = p_numer_mieszkania
    WHERE ID_ADRESU = p_id_adresu;
    COMMIT;
END;






/
--------------------------------------------------------
--  DDL for Procedure EDYTUJ_DARCZYNCE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHRONISKO"."EDYTUJ_DARCZYNCE" (
    p_id                  NUMBER,
    p_nazwa_uzytkownika   VARCHAR2,
    p_imie                VARCHAR2,
    p_nazwisko            VARCHAR2,
    p_mail                VARCHAR2
) AS
BEGIN
    UPDATE DARCZYNCY
    SET 
        NAZWA_UZYTKOWNIKA = p_nazwa_uzytkownika,
        IMIE              = p_imie,
        NAZWISKO          = p_nazwisko,
        MAIL              = p_mail
    WHERE 
        ID = p_id;

    COMMIT;
END EDYTUJ_DARCZYNCE;





/
--------------------------------------------------------
--  DDL for Procedure EDYTUJ_DAROWIZNE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHRONISKO"."EDYTUJ_DAROWIZNE" (
    p_id IN NUMBER,
    p_darczynca_id IN NUMBER,
    p_kwota IN NUMBER,
    p_data IN DATE
) AS
BEGIN
    -- Aktualizacja rekordu w tabeli REJESTR_DAROWIZN
    UPDATE SCHRONISKO.REJESTR_DAROWIZN
    SET DARCZYNCA_ID = p_darczynca_id,
        KWOTA = p_kwota,
        DATA = p_data
    WHERE ID = p_id;

    -- Sprawdzenie, czy rekord zosta� zaktualizowany
    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Nie znaleziono darowizny o podanym ID.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;





/
--------------------------------------------------------
--  DDL for Procedure EDYTUJ_KOJEC
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHRONISKO"."EDYTUJ_KOJEC" (
    p_id NUMBER,       -- ID kojca, kt�ry ma by� edytowany
    p_numer VARCHAR2,  -- Nowy numer kojca
    p_rozmiar VARCHAR2 -- Nowy rozmiar kojca
) AS
BEGIN
    -- Aktualizacja danych w tabeli Kojce
    UPDATE Kojce
    SET NUMER = p_numer,
        WIELKOSC = p_rozmiar
    WHERE KOJEC_ID = p_id; -- Identyfikacja kojca po jego ID
    COMMIT; -- Zatwierdzenie zmian
END;




/
--------------------------------------------------------
--  DDL for Procedure EDYTUJ_PRACOWNIKA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHRONISKO"."EDYTUJ_PRACOWNIKA" (
    p_id NUMBER,
    p_imie VARCHAR2,
    p_nazwisko VARCHAR2,
    p_pensja NUMBER,
    p_stanowisko VARCHAR2,
    p_adres_id NUMBER,
    p_data_zatrudnienia DATE
) AS
BEGIN
    UPDATE Pracownicy
    SET IMIE = p_imie,
        NAZWISKO = p_nazwisko,
        PENSJA = p_pensja,
        STANOWISKO = p_stanowisko,
        ADRES_ID = p_adres_id,
        DATA_ZATRUDNIENIA = p_data_zatrudnienia
    WHERE ID = p_id;
    COMMIT;
END;






/
--------------------------------------------------------
--  DDL for Procedure EDYTUJ_ZWIERZE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHRONISKO"."EDYTUJ_ZWIERZE" (
    p_id_zwierzecia NUMBER,
    p_imie VARCHAR2,
    p_rasa VARCHAR2,
    p_plec VARCHAR2,
    p_status VARCHAR2,
    p_kojec_id NUMBER,
    p_data_przyjecia DATE,
    p_wiek NUMBER,
    p_typ VARCHAR2
) AS
BEGIN
    UPDATE Zwierzeta
    SET IMIE = p_imie,
        RASA = p_rasa,
        PLEC = p_plec,
        STATUS = p_status,
        KOJEC_ID = p_kojec_id,
        DATA_PRZYJECIA = p_data_przyjecia,
        WIEK = p_wiek,
        TYP = p_typ
    WHERE ID = p_id_zwierzecia;
    COMMIT;
END;






/
--------------------------------------------------------
--  DDL for Procedure USUN_ADOPCJE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHRONISKO"."USUN_ADOPCJE" (
    p_id NUMBER
) AS
BEGIN
    -- Usuwamy rekord z tabeli REJESTR_ADOPCJI na podstawie ID adopcji
    DELETE FROM REJESTR_ADOPCJI WHERE ID_ADOPCJI = p_id;

    -- Zatwierdzamy transakcj�
    COMMIT;
END;






/
--------------------------------------------------------
--  DDL for Procedure USUN_ADRES
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHRONISKO"."USUN_ADRES" (
    p_id NUMBER
) AS
BEGIN
    DELETE FROM Adresy WHERE ID_ADRESU = p_id;
    COMMIT;
END;






/
--------------------------------------------------------
--  DDL for Procedure USUN_DARCZYNCE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHRONISKO"."USUN_DARCZYNCE" (
    p_id NUMBER
) AS
BEGIN
    DELETE FROM DARCZYNCY
    WHERE ID = p_id;

    COMMIT;
END USUN_DARCZYNCE;





/
--------------------------------------------------------
--  DDL for Procedure USUN_DAROWIZNE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHRONISKO"."USUN_DAROWIZNE" (
    p_id IN NUMBER
) AS
BEGIN
    -- Usuni�cie rekordu z tabeli REJESTR_DAROWIZN
    DELETE FROM SCHRONISKO.REJESTR_DAROWIZN
    WHERE ID = p_id;

    -- Sprawdzenie, czy rekord zosta� usuni�ty
    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'Nie znaleziono darowizny o podanym ID.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;





/
--------------------------------------------------------
--  DDL for Procedure USUN_KOJEC
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHRONISKO"."USUN_KOJEC" (
    p_id NUMBER
) AS
BEGIN
    -- Usuni�cie rekordu z tabeli Kojce na podstawie ID_KOJCA
    DELETE FROM Kojce WHERE KOJEC_ID = p_id;
    COMMIT;
END;




/
--------------------------------------------------------
--  DDL for Procedure USUN_PRACOWNIKA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHRONISKO"."USUN_PRACOWNIKA" (
    p_id NUMBER
) AS
BEGIN
    DELETE FROM Pracownicy WHERE ID = p_id;
    COMMIT;
END;






/
--------------------------------------------------------
--  DDL for Procedure USUN_ZWIERZE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHRONISKO"."USUN_ZWIERZE" (
    p_id NUMBER
) AS
BEGIN
    DELETE FROM Zwierzeta WHERE ID = p_id;
    COMMIT;
END;






/
--------------------------------------------------------
--  DDL for Package PAKIET_ADOPCJE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "SCHRONISKO"."PAKIET_ADOPCJE" 
is
procedure DODAJ_ADOPCJE;
procedure USUN_ADOPCJE;
function GET_ADOPTION_DETAILS return SYS_REFCURSOR;
function GET_AVAILABLE_ANIMALS return SYS_REFCURSOR;
function GET_KOORDYNATORZY_ADOPCJI return SYS_REFCURSOR;
end;





/
--------------------------------------------------------
--  DDL for Package PAKIET_ADRESY
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "SCHRONISKO"."PAKIET_ADRESY" 
is
procedure DODAJ_ADRES;
procedure EDYTUJ_ADRES;
procedure USUN_ADRES;
function GET_ADDRESSES return SYS_REFCURSOR;
end;





/
--------------------------------------------------------
--  DDL for Package PAKIET_DARCZYNCY
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "SCHRONISKO"."PAKIET_DARCZYNCY" 
is
procedure DODAJ_DARCZYNCE;
procedure EDYTUJ_DARCZYNCE;
procedure USUN_DARCZYNCE;
function GET_DARCZYNCY return SYS_REFCURSOR;
end;





/
--------------------------------------------------------
--  DDL for Package PAKIET_DAROWIZNY
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "SCHRONISKO"."PAKIET_DAROWIZNY" IS
    FUNCTION GET_DAROWIZNY RETURN SYS_REFCURSOR;
    PROCEDURE DODAJ_DAROWIZNE;
    PROCEDURE EDYTUJ_DAROWIZNE;
    PROCEDURE USUN_DAROWIZNE;
    FUNCTION GET_SUM_DONATIONS RETURN SYS_REFCURSOR;
    FUNCTION GET_AVG_DONATION RETURN SYS_REFCURSOR;
END;



/
--------------------------------------------------------
--  DDL for Package PAKIET_KOJCE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "SCHRONISKO"."PAKIET_KOJCE" 
is
procedure DODAJ_KOJEC;
procedure EDYTUJ_KOJEC;
procedure USUN_KOJEC;
function POBIERZZWIERZETAPRACOWNICY return SYS_REFCURSOR;
end;



/
--------------------------------------------------------
--  DDL for Package PAKIET_PRACOWNICY
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "SCHRONISKO"."PAKIET_PRACOWNICY" 
is
procedure DODAJ_PRACOWNIKA;
procedure EDYTUJ_PRACOWNIKA;
procedure USUN_PRACOWNIKA;
function GET_ADRESY return SYS_REFCURSOR;
function GET_PRACOWNICY_WITH_ADRESS return SYS_REFCURSOR;
function GET_FORMATTED_ADDRESSES return SYS_REFCURSOR;
function GET_SUM_SALARIES return SYS_REFCURSOR;
function GET_AVG_SALARY return SYS_REFCURSOR;
end;

/
--------------------------------------------------------
--  DDL for Package PAKIET_PRACOWNICY_ZWIERZETA
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "SCHRONISKO"."PAKIET_PRACOWNICY_ZWIERZETA" 
is
function GET_OPIEKUN return SYS_REFCURSOR;
function GET_SPRZATACZE return SYS_REFCURSOR;
function GET_WETERYNARZ return SYS_REFCURSOR;
function GET_KOORDYNATORZY_ADOPCJI return SYS_REFCURSOR;
function GET_ADOPTION_COORDINATORS_STATS return SYS_REFCURSOR;

end;

/
--------------------------------------------------------
--  DDL for Package PAKIET_ZWIERZETA
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "SCHRONISKO"."PAKIET_ZWIERZETA" 
is
procedure DODAJ_ZWIERZE;
procedure EDYTUJ_ZWIERZE;
procedure USUN_ZWIERZE;
function GET_KOJCE return SYS_REFCURSOR;
function GET_ANIMALS_AND_CAGES return SYS_REFCURSOR;
end;





/
--------------------------------------------------------
--  DDL for Function COUNT_MIXED_BREED_CATS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "SCHRONISKO"."COUNT_MIXED_BREED_CATS" 
RETURN NUMBER
IS
    mixed_breed_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO mixed_breed_count
    FROM zwierzeta
    WHERE rasa = 'Mieszaniec' AND typ = 'Kot';

    RETURN mixed_breed_count;
END;


/
--------------------------------------------------------
--  DDL for Function COUNT_MIXED_BREED_DOGS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "SCHRONISKO"."COUNT_MIXED_BREED_DOGS" 
RETURN NUMBER
IS
    mixed_breed_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO mixed_breed_count
    FROM zwierzeta
    WHERE rasa = 'Mieszaniec' AND typ = 'Pies';

    RETURN mixed_breed_count;
END;


/
--------------------------------------------------------
--  DDL for Function COUNT_NON_MIXED_BREED_CATS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "SCHRONISKO"."COUNT_NON_MIXED_BREED_CATS" 
RETURN NUMBER
IS
    non_mixed_breed_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO non_mixed_breed_count
    FROM zwierzeta
    WHERE rasa != 'Mieszaniec' AND typ = 'Kot';

    RETURN non_mixed_breed_count;
END;


/
--------------------------------------------------------
--  DDL for Function COUNT_NON_MIXED_BREED_DOGS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "SCHRONISKO"."COUNT_NON_MIXED_BREED_DOGS" 
RETURN NUMBER
IS
    non_mixed_breed_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO non_mixed_breed_count
    FROM zwierzeta
    WHERE rasa != 'Mieszaniec' AND typ = 'Pies';

    RETURN non_mixed_breed_count;
END;


/
--------------------------------------------------------
--  DDL for Function GET_ADDRESSES
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "SCHRONISKO"."GET_ADDRESSES" 
RETURN SYS_REFCURSOR
IS
    address_cursor SYS_REFCURSOR;
BEGIN
    OPEN address_cursor FOR
    SELECT 
        ID_ADRESU, 
        MIASTO, 
        KOD_POCZTOWY, 
        ULICA, 
        NUMER_DOMU, 
        NUMER_MIESZKANIA 
    FROM Adresy;

    RETURN address_cursor;
END;






/
--------------------------------------------------------
--  DDL for Function GET_ADOPTION_COORDINATORS_STATS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "SCHRONISKO"."GET_ADOPTION_COORDINATORS_STATS" 
RETURN SYS_REFCURSOR
IS
    result_cursor SYS_REFCURSOR;
BEGIN
    OPEN result_cursor FOR
    SELECT 
        imie, 
        nazwisko, 
        COUNT(nazwisko) AS Liczba_zwierzat
    FROM (
        SELECT 
            p.id, 
            p.imie,  
            p.nazwisko, 
            p.stanowisko,  
            pw.ZWIERZE_ID
        FROM pracownicy p
        INNER JOIN pracownik_zwierzeta pw 
            ON p.id = pw.pracownik_id
        WHERE p.stanowisko = 'Koordynator Adopcji'
    )
    GROUP BY imie, nazwisko;

    RETURN result_cursor;
END;



/
--------------------------------------------------------
--  DDL for Function GET_ADOPTION_DETAILS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "SCHRONISKO"."GET_ADOPTION_DETAILS" 
RETURN SYS_REFCURSOR
IS
    adoption_cursor SYS_REFCURSOR;
BEGIN
    OPEN adoption_cursor FOR
    SELECT 
        ra.ID_ADOPCJI, 
        z.IMIE || ' (' || z.RASA || ')' || ' - ' || k.NUMER AS ZWIERZE, 
        p.IMIE || ' ' || p.NAZWISKO AS PRACOWNIK, 
        ad.MIASTO || ', ' || ad.KOD_POCZTOWY || ', ' || ad.ULICA || ' ' || ad.NUMER_DOMU || COALESCE('/' || ad.NUMER_MIESZKANIA, '') AS ADRES, 
        ra.DATA_ADOPCJI, 
        ra.imie || ' ' || ra.nazwisko || ' ' || ra.numer_telefonu AS DANE_ADOPTUJACEGO
    FROM REJESTR_ADOPCJI ra
    LEFT JOIN PRACOWNICY p ON ra.PRACOWNIK_ID = p.ID
    LEFT JOIN ZWIERZETA z ON ra.ZWIERZE_ID = z.ID
    LEFT JOIN KOJCE k ON z.KOJEC_ID = k.KOJEC_ID
    LEFT JOIN ADRESY ad ON ra.ADRES_ID = ad.ID_ADRESU;

    RETURN adoption_cursor;
END;






/
--------------------------------------------------------
--  DDL for Function GET_ADRESY
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "SCHRONISKO"."GET_ADRESY" 
RETURN SYS_REFCURSOR
IS
    adresy_cursor SYS_REFCURSOR;
BEGIN
    OPEN adresy_cursor FOR
    SELECT ID_ADRESU, MIASTO, KOD_POCZTOWY, ULICA, NUMER_DOMU, NUMER_MIESZKANIA 
    FROM Adresy;

    RETURN adresy_cursor;
END;






/
--------------------------------------------------------
--  DDL for Function GET_ANIMALS_AND_CAGES
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "SCHRONISKO"."GET_ANIMALS_AND_CAGES" 
RETURN SYS_REFCURSOR
IS
    animal_cursor SYS_REFCURSOR;
BEGIN
    OPEN animal_cursor FOR
    SELECT z.ID, z.IMIE, z.RASA, z.PLEC, z.STATUS, k.NUMER, z.DATA_PRZYJECIA, z.WIEK, z.TYP, k.WIELKOSC
    FROM Zwierzeta z
    LEFT JOIN KOJCE k ON z.KOJEC_ID = k.KOJEC_ID;

    RETURN animal_cursor;
END;





/
--------------------------------------------------------
--  DDL for Function GET_AVAILABLE_ANIMALS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "SCHRONISKO"."GET_AVAILABLE_ANIMALS" 
RETURN SYS_REFCURSOR
IS
    result_cursor SYS_REFCURSOR;
BEGIN
    OPEN result_cursor FOR
    SELECT z.ID, z.IMIE, z.RASA, k.NUMER 
    FROM ZWIERZETA z
    LEFT JOIN KOJCE k ON z.KOJEC_ID = k.KOJEC_ID
    WHERE z.STATUS = 'Dostepny';

    RETURN result_cursor;
END;






/
--------------------------------------------------------
--  DDL for Function GET_AVG_DONATION
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "SCHRONISKO"."GET_AVG_DONATION" 
return SYS_REFCURSOR
IS
    result_cursor SYS_REFCURSOR;
BEGIN
    OPEN result_cursor FOR
    SELECT avg(kwota)
    FROM rejestr_darowizn;

    RETURN result_cursor;
END;



/
--------------------------------------------------------
--  DDL for Function GET_AVG_SALARY
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "SCHRONISKO"."GET_AVG_SALARY" 
return SYS_REFCURSOR
IS
    result_cursor SYS_REFCURSOR;
BEGIN
    OPEN result_cursor FOR
    SELECT avg(pensja)
    FROM PRACOWNICY;

    RETURN result_cursor;
END;



/
--------------------------------------------------------
--  DDL for Function GET_DARCZYNCY
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "SCHRONISKO"."GET_DARCZYNCY" 
RETURN SYS_REFCURSOR
IS
    darczyncy_cursor SYS_REFCURSOR;
BEGIN
    OPEN darczyncy_cursor FOR
    SELECT 
        ID, 
        NAZWA_UZYTKOWNIKA, 
        IMIE, 
        NAZWISKO, 
        MAIL 
    FROM darczyncy;

    RETURN darczyncy_cursor;
END;





/
--------------------------------------------------------
--  DDL for Function GET_DAROWIZNY
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "SCHRONISKO"."GET_DAROWIZNY" 
RETURN SYS_REFCURSOR
IS
    darowizny_cursor SYS_REFCURSOR;
BEGIN
    OPEN darowizny_cursor FOR
    SELECT 
        r.ID, 
        r.DARCZYNCA_ID, 
        d.NAZWA_UZYTKOWNIKA, 
        r.KWOTA, 
        r.DATA 
    FROM REJESTR_DAROWIZN r
    JOIN DARCZYNCY d ON r.DARCZYNCA_ID = d.ID;

    RETURN darowizny_cursor;
END;




/
--------------------------------------------------------
--  DDL for Function GET_FORMATTED_ADDRESSES
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "SCHRONISKO"."GET_FORMATTED_ADDRESSES" 
RETURN SYS_REFCURSOR
IS
    result_cursor SYS_REFCURSOR;
BEGIN
    OPEN result_cursor FOR
    SELECT 
        ID_ADRESU, 
        MIASTO || ', ' || KOD_POCZTOWY || ', ' || ULICA || ' ' || NUMER_DOMU || 
        CASE WHEN NUMER_MIESZKANIA IS NOT NULL THEN '/' || NUMER_MIESZKANIA ELSE '' END AS FULL_ADDRESS
    FROM Adresy;

    RETURN result_cursor;
END;






/
--------------------------------------------------------
--  DDL for Function GET_KOJCE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "SCHRONISKO"."GET_KOJCE" 
RETURN SYS_REFCURSOR
IS
    kojec_cursor SYS_REFCURSOR;
BEGIN
    OPEN kojec_cursor FOR
    SELECT KOJEC_ID, NUMER, WIELKOSC
    FROM KOJCE;

    RETURN kojec_cursor;
END;




/
--------------------------------------------------------
--  DDL for Function GET_KOORDYNATORZY_ADOPCJI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "SCHRONISKO"."GET_KOORDYNATORZY_ADOPCJI" 
RETURN SYS_REFCURSOR
IS
    result_cursor SYS_REFCURSOR;
BEGIN
    OPEN result_cursor FOR
        SELECT ID, IMIE, NAZWISKO 
        FROM Pracownicy 
        WHERE STANOWISKO = 'Koordynator Adopcji';

    RETURN result_cursor;
END;






/
--------------------------------------------------------
--  DDL for Function GET_OPIEKUN
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "SCHRONISKO"."GET_OPIEKUN" 
RETURN SYS_REFCURSOR
IS
    result_cursor SYS_REFCURSOR;
BEGIN
    OPEN result_cursor FOR
        SELECT ID, IMIE, NAZWISKO 
        FROM Pracownicy 
        WHERE STANOWISKO = 'Opiekun Zwierzat';

    RETURN result_cursor;
END;





/
--------------------------------------------------------
--  DDL for Function GET_PRACOWNICY_WITH_ADDRESS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "SCHRONISKO"."GET_PRACOWNICY_WITH_ADDRESS" 
RETURN SYS_REFCURSOR
IS
    result_cursor SYS_REFCURSOR;
BEGIN
    OPEN result_cursor FOR
    SELECT 
        p.ID, 
        p.IMIE, 
        p.NAZWISKO, 
        p.PENSJA, 
        p.STANOWISKO, 
        a.ULICA || ' ' || a.NUMER_DOMU || COALESCE('/' || a.NUMER_MIESZKANIA, '') || ', ' || a.MIASTO || ', ' || a.KOD_POCZTOWY AS FULL_ADDRESS, 
        p.DATA_ZATRUDNIENIA
    FROM Pracownicy p
    LEFT JOIN Adresy a ON p.ADRES_ID = a.ID_ADRESU;

    RETURN result_cursor;
END;






/
--------------------------------------------------------
--  DDL for Function GET_SPRZATACZE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "SCHRONISKO"."GET_SPRZATACZE" 
RETURN SYS_REFCURSOR
IS
    result_cursor SYS_REFCURSOR;
BEGIN
    OPEN result_cursor FOR
        SELECT ID, IMIE, NAZWISKO 
        FROM Pracownicy 
        WHERE STANOWISKO = 'Sprzatacz';

    RETURN result_cursor;
END;





/
--------------------------------------------------------
--  DDL for Function GET_SUM_DONATIONS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "SCHRONISKO"."GET_SUM_DONATIONS" 
return SYS_REFCURSOR
IS
    result_cursor SYS_REFCURSOR;
BEGIN
    OPEN result_cursor FOR
    SELECT sum(kwota)
    FROM rejestr_darowizn;

    RETURN result_cursor;
END;



/
--------------------------------------------------------
--  DDL for Function GET_SUM_SALARIES
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "SCHRONISKO"."GET_SUM_SALARIES" 
return SYS_REFCURSOR
IS
    result_cursor SYS_REFCURSOR;
BEGIN
    OPEN result_cursor FOR
    SELECT sum(pensja)
    FROM PRACOWNICY;

    RETURN result_cursor;
END;



/
--------------------------------------------------------
--  DDL for Function GET_WETERYNARZ
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "SCHRONISKO"."GET_WETERYNARZ" 
RETURN SYS_REFCURSOR
IS
    result_cursor SYS_REFCURSOR;
BEGIN
    OPEN result_cursor FOR
        SELECT ID, IMIE, NAZWISKO 
        FROM Pracownicy 
        WHERE STANOWISKO = 'Weterynarz';

    RETURN result_cursor;
END;





/
--------------------------------------------------------
--  DDL for Function POBIERZZWIERZETAPRACOWNICY
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "SCHRONISKO"."POBIERZZWIERZETAPRACOWNICY" 
RETURN SYS_REFCURSOR
AS
    wynik SYS_REFCURSOR;
BEGIN
    OPEN wynik FOR
        SELECT 
            z.ID AS ZWIERZE_ID, 
            z.IMIE AS ZWIERZE_IMIE, 
            z.RASA AS ZWIERZE_RASA,
            z.TYP AS ZWIERZE_TYP,
            p.ID AS PRACOWNIK_ID, 
            p.IMIE AS PRACOWNIK_IMIE, 
            p.NAZWISKO AS PRACOWNIK_NAZWISKO, 
            p.STANOWISKO AS PRACOWNIK_STANOWISKO
        FROM 
            zwierzeta z
        LEFT JOIN 
            pracownik_zwierzeta pw ON z.ID = pw.zwierze_id
        LEFT JOIN 
            pracownicy p ON pw.pracownik_id = p.ID
        ORDER BY 
            z.ID;

    RETURN wynik;
END;




/
--------------------------------------------------------
--  Constraints for Table ADRESY
--------------------------------------------------------

  ALTER TABLE "SCHRONISKO"."ADRESY" MODIFY ("MIASTO" NOT NULL ENABLE);
  ALTER TABLE "SCHRONISKO"."ADRESY" MODIFY ("KOD_POCZTOWY" NOT NULL ENABLE);
  ALTER TABLE "SCHRONISKO"."ADRESY" ADD PRIMARY KEY ("ID_ADRESU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DARCZYNCY
--------------------------------------------------------

  ALTER TABLE "SCHRONISKO"."DARCZYNCY" MODIFY ("NAZWA_UZYTKOWNIKA" NOT NULL ENABLE);
  ALTER TABLE "SCHRONISKO"."DARCZYNCY" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCHRONISKO"."DARCZYNCY" ADD UNIQUE ("NAZWA_UZYTKOWNIKA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCHRONISKO"."DARCZYNCY" ADD UNIQUE ("MAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KOJCE
--------------------------------------------------------

  ALTER TABLE "SCHRONISKO"."KOJCE" ADD PRIMARY KEY ("KOJEC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRACOWNICY
--------------------------------------------------------

  ALTER TABLE "SCHRONISKO"."PRACOWNICY" MODIFY ("IMIE" NOT NULL ENABLE);
  ALTER TABLE "SCHRONISKO"."PRACOWNICY" MODIFY ("NAZWISKO" NOT NULL ENABLE);
  ALTER TABLE "SCHRONISKO"."PRACOWNICY" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRACOWNIK_ZWIERZETA
--------------------------------------------------------

  ALTER TABLE "SCHRONISKO"."PRACOWNIK_ZWIERZETA" ADD PRIMARY KEY ("PRACOWNIK_ID", "ZWIERZE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REJESTR_ADOPCJI
--------------------------------------------------------

  ALTER TABLE "SCHRONISKO"."REJESTR_ADOPCJI" MODIFY ("DATA_ADOPCJI" NOT NULL ENABLE);
  ALTER TABLE "SCHRONISKO"."REJESTR_ADOPCJI" ADD PRIMARY KEY ("ID_ADOPCJI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REJESTR_DAROWIZN
--------------------------------------------------------

  ALTER TABLE "SCHRONISKO"."REJESTR_DAROWIZN" MODIFY ("KWOTA" NOT NULL ENABLE);
  ALTER TABLE "SCHRONISKO"."REJESTR_DAROWIZN" MODIFY ("DATA" NOT NULL ENABLE);
  ALTER TABLE "SCHRONISKO"."REJESTR_DAROWIZN" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ZWIERZETA
--------------------------------------------------------

  ALTER TABLE "SCHRONISKO"."ZWIERZETA" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRACOWNICY
--------------------------------------------------------

  ALTER TABLE "SCHRONISKO"."PRACOWNICY" ADD FOREIGN KEY ("ADRES_ID")
	  REFERENCES "SCHRONISKO"."ADRESY" ("ID_ADRESU") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRACOWNIK_ZWIERZETA
--------------------------------------------------------

  ALTER TABLE "SCHRONISKO"."PRACOWNIK_ZWIERZETA" ADD FOREIGN KEY ("PRACOWNIK_ID")
	  REFERENCES "SCHRONISKO"."PRACOWNICY" ("ID") ENABLE;
  ALTER TABLE "SCHRONISKO"."PRACOWNIK_ZWIERZETA" ADD FOREIGN KEY ("ZWIERZE_ID")
	  REFERENCES "SCHRONISKO"."ZWIERZETA" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REJESTR_ADOPCJI
--------------------------------------------------------

  ALTER TABLE "SCHRONISKO"."REJESTR_ADOPCJI" ADD FOREIGN KEY ("ZWIERZE_ID")
	  REFERENCES "SCHRONISKO"."ZWIERZETA" ("ID") ENABLE;
  ALTER TABLE "SCHRONISKO"."REJESTR_ADOPCJI" ADD FOREIGN KEY ("PRACOWNIK_ID")
	  REFERENCES "SCHRONISKO"."PRACOWNICY" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REJESTR_DAROWIZN
--------------------------------------------------------

  ALTER TABLE "SCHRONISKO"."REJESTR_DAROWIZN" ADD FOREIGN KEY ("DARCZYNCA_ID")
	  REFERENCES "SCHRONISKO"."DARCZYNCY" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ZWIERZETA
--------------------------------------------------------

  ALTER TABLE "SCHRONISKO"."ZWIERZETA" ADD FOREIGN KEY ("KOJEC_ID")
	  REFERENCES "SCHRONISKO"."KOJCE" ("KOJEC_ID") ENABLE;
