--------------------------------------------------------
--  File created - niedziela-grudnia-08-2024   
--------------------------------------------------------
DROP SEQUENCE "SCHRONISKO"."ADRESY_SEQ";
DROP SEQUENCE "SCHRONISKO"."PRACOWNICY_SEQ";
DROP SEQUENCE "SCHRONISKO"."REJESTR_ADOPCJI_SEQ";
DROP SEQUENCE "SCHRONISKO"."SEQ_ADOPCJE_ID";
DROP SEQUENCE "SCHRONISKO"."ZWIERZETA_SEQ";
DROP SEQUENCE "SCHRONISKO"."SEQ_ADOPCJE_ID";
DROP SEQUENCE "SCHRONISKO"."ADRESY_SEQ";
DROP SEQUENCE "SCHRONISKO"."PRACOWNICY_SEQ";
DROP SEQUENCE "SCHRONISKO"."ZWIERZETA_SEQ";
DROP SEQUENCE "SCHRONISKO"."DARCZYNCY_SEQ";
DROP SEQUENCE "SCHRONISKO"."DAROWIZNY_SEQ";
DROP TABLE "SCHRONISKO"."ADRESY" cascade constraints;
DROP TABLE "SCHRONISKO"."DARCZYNCY" cascade constraints;
DROP TABLE "SCHRONISKO"."KOJCE" cascade constraints;
DROP TABLE "SCHRONISKO"."PRACOWNICY" cascade constraints;
DROP TABLE "SCHRONISKO"."PRACOWNIK_ZWIERZETA" cascade constraints;
DROP TABLE "SCHRONISKO"."REJESTR_ADOPCJI" cascade constraints;
DROP TABLE "SCHRONISKO"."REJESTR_DAROWIZN" cascade constraints;
DROP TABLE "SCHRONISKO"."ZWIERZETA" cascade constraints;
DROP TABLE "SCHRONISKO"."ADRESY" cascade constraints;
DROP TABLE "SCHRONISKO"."PRACOWNICY" cascade constraints;
DROP TABLE "SCHRONISKO"."ZWIERZETA" cascade constraints;
DROP TABLE "SCHRONISKO"."DARCZYNCY" cascade constraints;
DROP TABLE "SCHRONISKO"."KOJCE" cascade constraints;
DROP TABLE "SCHRONISKO"."PRACOWNIK_ZWIERZETA" cascade constraints;
DROP TABLE "SCHRONISKO"."REJESTR_ADOPCJI" cascade constraints;
DROP TABLE "SCHRONISKO"."REJESTR_DAROWIZN" cascade constraints;
DROP PROCEDURE "SCHRONISKO"."DODAJ_ADOPCJE";
DROP PROCEDURE "SCHRONISKO"."DODAJ_ADRES";
DROP PROCEDURE "SCHRONISKO"."DODAJ_PRACOWNIKA";
DROP PROCEDURE "SCHRONISKO"."DODAJ_ZWIERZE";
DROP PROCEDURE "SCHRONISKO"."DODAJ_DARCZYNCE";
DROP PROCEDURE "SCHRONISKO"."DODAJ_DAROWIZNE";
DROP PROCEDURE "SCHRONISKO"."EDYTUJ_ADRES";
DROP PROCEDURE "SCHRONISKO"."EDYTUJ_PRACOWNIKA";
DROP PROCEDURE "SCHRONISKO"."EDYTUJ_ZWIERZE";
DROP PROCEDURE "SCHRONISKO"."EDYTUJ_DARCZYNCE";
DROP PROCEDURE "SCHRONISKO"."EDYTUJ_DAROWIZNE";
DROP PROCEDURE "SCHRONISKO"."USUN_ADOPCJE";
DROP PROCEDURE "SCHRONISKO"."USUN_ADRES";
DROP PROCEDURE "SCHRONISKO"."USUN_PRACOWNIKA";
DROP PROCEDURE "SCHRONISKO"."USUN_ZWIERZE";
DROP PROCEDURE "SCHRONISKO"."USUN_DARCZYNCE";
DROP PROCEDURE "SCHRONISKO"."USUN_DAROWIZNE";
DROP FUNCTION "SCHRONISKO"."GET_ADDRESSES";
DROP FUNCTION "SCHRONISKO"."GET_ADOPTION_DETAILS";
DROP FUNCTION "SCHRONISKO"."GET_ADRESY";
DROP FUNCTION "SCHRONISKO"."GET_ANIMALS_AND_CAGES";
DROP FUNCTION "SCHRONISKO"."GET_AVAILABLE_ANIMALS";
DROP FUNCTION "SCHRONISKO"."GET_FORMATTED_ADDRESSES";
DROP FUNCTION "SCHRONISKO"."GET_KOJCE";
DROP FUNCTION "SCHRONISKO"."GET_KOORDYNATORZY_ADOPCJI";
DROP FUNCTION "SCHRONISKO"."GET_PRACOWNICY_WITH_ADDRESS";
DROP FUNCTION "SCHRONISKO"."GET_PRACOWNICY_WITH_ADDRESS";
DROP FUNCTION "SCHRONISKO"."GET_DARCZYNCY";

--------------------------------------------------------
--  DDL for Sequence ADRESY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SCHRONISKO"."ADRESY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 51 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PRACOWNICY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SCHRONISKO"."PRACOWNICY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 51 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence REJESTR_ADOPCJI_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SCHRONISKO"."REJESTR_ADOPCJI_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 5 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ADOPCJE_ID
--------------------------------------------------------

   CREATE SEQUENCE  "SCHRONISKO"."SEQ_ADOPCJE_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 16 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence ZWIERZETA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SCHRONISKO"."ZWIERZETA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 34 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ADOPCJE_ID
--------------------------------------------------------

   CREATE SEQUENCE  "SCHRONISKO"."SEQ_ADOPCJE_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 16 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence ADRESY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SCHRONISKO"."ADRESY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 51 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PRACOWNICY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SCHRONISKO"."PRACOWNICY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 51 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence ZWIERZETA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SCHRONISKO"."ZWIERZETA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 34 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table ADRESY
--------------------------------------------------------

  CREATE TABLE "SCHRONISKO"."ADRESY" 
   (	"ID_ADRESU" NUMBER, 
	"MIASTO" VARCHAR2(50 BYTE), 
	"KOD_POCZTOWY" VARCHAR2(10 BYTE), 
	"ULICA" VARCHAR2(100 BYTE), 
	"NUMER_DOMU" VARCHAR2(10 BYTE), 
	"NUMER_MIESZKANIA" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DARCZYNCY
--------------------------------------------------------

  CREATE TABLE "SCHRONISKO"."DARCZYNCY" 
   (	"ID" NUMBER, 
	"NAZWA_UZYTKOWNIKA" VARCHAR2(50 BYTE), 
	"IMIE" VARCHAR2(50 BYTE), 
	"NAZWISKO" VARCHAR2(50 BYTE), 
	"MAIL" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KOJCE
--------------------------------------------------------

  CREATE TABLE "SCHRONISKO"."KOJCE" 
   (	"KOJEC_ID" NUMBER, 
	"WIELKOSC" VARCHAR2(20 BYTE), 
	"NUMER" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRACOWNICY
--------------------------------------------------------

  CREATE TABLE "SCHRONISKO"."PRACOWNICY" 
   (	"ID" NUMBER, 
	"IMIE" VARCHAR2(50 BYTE), 
	"NAZWISKO" VARCHAR2(50 BYTE), 
	"PENSJA" NUMBER(10,2), 
	"STANOWISKO" VARCHAR2(100 BYTE), 
	"ADRES_ID" NUMBER, 
	"DATA_ZATRUDNIENIA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRACOWNIK_ZWIERZETA
--------------------------------------------------------

  CREATE TABLE "SCHRONISKO"."PRACOWNIK_ZWIERZETA" 
   (	"PRACOWNIK_ID" NUMBER, 
	"ZWIERZE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REJESTR_ADOPCJI
--------------------------------------------------------

  CREATE TABLE "SCHRONISKO"."REJESTR_ADOPCJI" 
   (	"ID_ADOPCJI" NUMBER, 
	"DATA_ADOPCJI" DATE, 
	"ZWIERZE_ID" NUMBER, 
	"PRACOWNIK_ID" NUMBER, 
	"IMIE" VARCHAR2(100 BYTE), 
	"NAZWISKO" VARCHAR2(100 BYTE), 
	"ADRES_ID" NUMBER, 
	"NUMER_TELEFONU" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REJESTR_DAROWIZN
--------------------------------------------------------

  CREATE TABLE "SCHRONISKO"."REJESTR_DAROWIZN" 
   (	"ID" NUMBER, 
	"DARCZYNCA_ID" NUMBER, 
	"KWOTA" NUMBER(10,2), 
	"DATA" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ZWIERZETA
--------------------------------------------------------

  CREATE TABLE "SCHRONISKO"."ZWIERZETA" 
   (	"ID" NUMBER, 
	"IMIE" VARCHAR2(50 BYTE), 
	"RASA" VARCHAR2(50 BYTE), 
	"PLEC" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(50 BYTE), 
	"KOJEC_ID" NUMBER, 
	"DATA_PRZYJECIA" DATE, 
	"WIEK" NUMBER, 
	"TYP" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ADRESY
--------------------------------------------------------

  CREATE TABLE "SCHRONISKO"."ADRESY" 
   (	"ID_ADRESU" NUMBER, 
	"MIASTO" VARCHAR2(50 BYTE), 
	"KOD_POCZTOWY" VARCHAR2(10 BYTE), 
	"ULICA" VARCHAR2(100 BYTE), 
	"NUMER_DOMU" VARCHAR2(10 BYTE), 
	"NUMER_MIESZKANIA" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRACOWNICY
--------------------------------------------------------

  CREATE TABLE "SCHRONISKO"."PRACOWNICY" 
   (	"ID" NUMBER, 
	"IMIE" VARCHAR2(50 BYTE), 
	"NAZWISKO" VARCHAR2(50 BYTE), 
	"PENSJA" NUMBER(10,2), 
	"STANOWISKO" VARCHAR2(100 BYTE), 
	"ADRES_ID" NUMBER, 
	"DATA_ZATRUDNIENIA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ZWIERZETA
--------------------------------------------------------

  CREATE TABLE "SCHRONISKO"."ZWIERZETA" 
   (	"ID" NUMBER, 
	"IMIE" VARCHAR2(50 BYTE), 
	"RASA" VARCHAR2(50 BYTE), 
	"PLEC" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(50 BYTE), 
	"KOJEC_ID" NUMBER, 
	"DATA_PRZYJECIA" DATE, 
	"WIEK" NUMBER, 
	"TYP" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DARCZYNCY
--------------------------------------------------------

  CREATE TABLE "SCHRONISKO"."DARCZYNCY" 
   (	"ID" NUMBER, 
	"NAZWA_UZYTKOWNIKA" VARCHAR2(50 BYTE), 
	"IMIE" VARCHAR2(50 BYTE), 
	"NAZWISKO" VARCHAR2(50 BYTE), 
	"MAIL" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KOJCE
--------------------------------------------------------

  CREATE TABLE "SCHRONISKO"."KOJCE" 
   (	"KOJEC_ID" NUMBER, 
	"WIELKOSC" VARCHAR2(20 BYTE), 
	"NUMER" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRACOWNIK_ZWIERZETA
--------------------------------------------------------

  CREATE TABLE "SCHRONISKO"."PRACOWNIK_ZWIERZETA" 
   (	"PRACOWNIK_ID" NUMBER, 
	"ZWIERZE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REJESTR_ADOPCJI
--------------------------------------------------------

  CREATE TABLE "SCHRONISKO"."REJESTR_ADOPCJI" 
   (	"ID_ADOPCJI" NUMBER, 
	"DATA_ADOPCJI" DATE, 
	"ZWIERZE_ID" NUMBER, 
	"PRACOWNIK_ID" NUMBER, 
	"IMIE" VARCHAR2(100 BYTE), 
	"NAZWISKO" VARCHAR2(100 BYTE), 
	"ADRES_ID" NUMBER, 
	"NUMER_TELEFONU" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REJESTR_DAROWIZN
--------------------------------------------------------

  CREATE TABLE "SCHRONISKO"."REJESTR_DAROWIZN" 
   (	"ID" NUMBER, 
	"DARCZYNCA_ID" NUMBER, 
	"KWOTA" NUMBER(10,2), 
	"DATA" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into SCHRONISKO.ADRESY
SET DEFINE OFF;
Insert into SCHRONISKO.ADRESY (ID_ADRESU,MIASTO,KOD_POCZTOWY,ULICA,NUMER_DOMU,NUMER_MIESZKANIA) values ('1','Warszawa','00-001','Marsza³kowska','12','1');
Insert into SCHRONISKO.ADRESY (ID_ADRESU,MIASTO,KOD_POCZTOWY,ULICA,NUMER_DOMU,NUMER_MIESZKANIA) values ('2','Kraków','30-001','Floriañska','25','2');
Insert into SCHRONISKO.ADRESY (ID_ADRESU,MIASTO,KOD_POCZTOWY,ULICA,NUMER_DOMU,NUMER_MIESZKANIA) values ('3','Poznañ','60-001','Wielka','15','3');
Insert into SCHRONISKO.ADRESY (ID_ADRESU,MIASTO,KOD_POCZTOWY,ULICA,NUMER_DOMU,NUMER_MIESZKANIA) values ('4','Wroc³aw','50-001','Œwidnicka','8','4');
Insert into SCHRONISKO.ADRESY (ID_ADRESU,MIASTO,KOD_POCZTOWY,ULICA,NUMER_DOMU,NUMER_MIESZKANIA) values ('5','Gdañsk','80-001','D³uga','19','5');
Insert into SCHRONISKO.ADRESY (ID_ADRESU,MIASTO,KOD_POCZTOWY,ULICA,NUMER_DOMU,NUMER_MIESZKANIA) values ('6','Szczecin','70-001','Pilsudskiego','3','6');
Insert into SCHRONISKO.ADRESY (ID_ADRESU,MIASTO,KOD_POCZTOWY,ULICA,NUMER_DOMU,NUMER_MIESZKANIA) values ('8','£ódŸ','90-001','Piotrkowska','11','8');
REM INSERTING into SCHRONISKO.DARCZYNCY
SET DEFINE OFF;
REM INSERTING into SCHRONISKO.KOJCE
SET DEFINE OFF;
Insert into SCHRONISKO.KOJCE (KOJEC_ID,WIELKOSC,NUMER) values ('1','Ma³y','K01DOG');
Insert into SCHRONISKO.KOJCE (KOJEC_ID,WIELKOSC,NUMER) values ('2','Œredni','K02DOG');
Insert into SCHRONISKO.KOJCE (KOJEC_ID,WIELKOSC,NUMER) values ('3','Du¿y','K03DOG');
Insert into SCHRONISKO.KOJCE (KOJEC_ID,WIELKOSC,NUMER) values ('4','Ma³y','K04DOG');
Insert into SCHRONISKO.KOJCE (KOJEC_ID,WIELKOSC,NUMER) values ('5','Œredni','K05DOG');
Insert into SCHRONISKO.KOJCE (KOJEC_ID,WIELKOSC,NUMER) values ('6','Du¿y','K06DOG');
Insert into SCHRONISKO.KOJCE (KOJEC_ID,WIELKOSC,NUMER) values ('7','Ma³y','K07DOG');
Insert into SCHRONISKO.KOJCE (KOJEC_ID,WIELKOSC,NUMER) values ('8','Œredni','K08DOG');
Insert into SCHRONISKO.KOJCE (KOJEC_ID,WIELKOSC,NUMER) values ('9','Du¿y','K09DOG');
Insert into SCHRONISKO.KOJCE (KOJEC_ID,WIELKOSC,NUMER) values ('10','Œredni','K10DOG');
Insert into SCHRONISKO.KOJCE (KOJEC_ID,WIELKOSC,NUMER) values ('11','Ma³y','K11CAT');
Insert into SCHRONISKO.KOJCE (KOJEC_ID,WIELKOSC,NUMER) values ('12','Œredni','K12CAT');
Insert into SCHRONISKO.KOJCE (KOJEC_ID,WIELKOSC,NUMER) values ('13','Du¿y','K13CAT');
REM INSERTING into SCHRONISKO.PRACOWNICY
SET DEFINE OFF;
Insert into SCHRONISKO.PRACOWNICY (ID,IMIE,NAZWISKO,PENSJA,STANOWISKO,ADRES_ID,DATA_ZATRUDNIENIA) values ('1','Anna','Kowalska','4500','Weterynarz','1',to_date('23/05/10','RR/MM/DD'));
Insert into SCHRONISKO.PRACOWNICY (ID,IMIE,NAZWISKO,PENSJA,STANOWISKO,ADRES_ID,DATA_ZATRUDNIENIA) values ('2','Piotr','Nowak','5000','Weterynarz','2',to_date('22/11/23','RR/MM/DD'));
Insert into SCHRONISKO.PRACOWNICY (ID,IMIE,NAZWISKO,PENSJA,STANOWISKO,ADRES_ID,DATA_ZATRUDNIENIA) values ('3','Ewa','Zieliñska','2500','Sprz¹tacz','3',to_date('24/01/01','RR/MM/DD'));
Insert into SCHRONISKO.PRACOWNICY (ID,IMIE,NAZWISKO,PENSJA,STANOWISKO,ADRES_ID,DATA_ZATRUDNIENIA) values ('4','Krzysztof','Wójcik','2600','Sprz¹tacz','4',to_date('23/09/10','RR/MM/DD'));
Insert into SCHRONISKO.PRACOWNICY (ID,IMIE,NAZWISKO,PENSJA,STANOWISKO,ADRES_ID,DATA_ZATRUDNIENIA) values ('5','Monika','Lewandowska','3000','Opiekun Zwierz¹t','5',to_date('24/02/15','RR/MM/DD'));
Insert into SCHRONISKO.PRACOWNICY (ID,IMIE,NAZWISKO,PENSJA,STANOWISKO,ADRES_ID,DATA_ZATRUDNIENIA) values ('6','Tomasz','Szymañski','3200','Opiekun Zwierz¹t','6',to_date('23/06/12','RR/MM/DD'));
Insert into SCHRONISKO.PRACOWNICY (ID,IMIE,NAZWISKO,PENSJA,STANOWISKO,ADRES_ID,DATA_ZATRUDNIENIA) values ('31','123','123','123','Koordynator Adopcji','3',to_date('24/12/02','RR/MM/DD'));
Insert into SCHRONISKO.PRACOWNICY (ID,IMIE,NAZWISKO,PENSJA,STANOWISKO,ADRES_ID,DATA_ZATRUDNIENIA) values ('8','Marek','Jankowski','6000','Koordynator Adopcji','8',to_date('22/08/05','RR/MM/DD'));
REM INSERTING into SCHRONISKO.PRACOWNIK_ZWIERZETA
SET DEFINE OFF;
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('1','5');
Insert into SCHRONISKO.PRACOWNIK_ZWIERZETA (PRACOWNIK_ID,ZWIERZE_ID) values ('3','5');
REM INSERTING into SCHRONISKO.REJESTR_ADOPCJI
SET DEFINE OFF;
REM INSERTING into SCHRONISKO.REJESTR_DAROWIZN
SET DEFINE OFF;
REM INSERTING into SCHRONISKO.ZWIERZETA
SET DEFINE OFF;
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('1','Ares','Mieszaniec','Male','Adoptowany','1',to_date('24/11/21','RR/MM/DD'),'3','Pies');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('2','Rex','Owczarek niemiecki','Male','Dostêpny','2',to_date('24/10/15','RR/MM/DD'),'5','Pies');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('3','Azor','Mieszaniec','Male','Dostepny','3',to_date('24/07/01','RR/MM/DD'),'4','Pies');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('4','Luna','Labrador','Female','Dostepny','4',to_date('24/09/05','RR/MM/DD'),'2','Pies');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('5','Max','Mieszaniec','Male','Dostepny','5',to_date('22/09/16','RR/MM/DD'),'1','Pies');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('6','Bella','Mieszaniec','Female','Dostepny','6',to_date('24/10/29','RR/MM/DD'),'6','Pies');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('7','Charlie','Beagle','Male','Dostepny','7',to_date('24/08/10','RR/MM/DD'),'3','Pies');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('8','Rocky','Mieszaniec','Male','Dostepny','8',to_date('24/02/20','RR/MM/DD'),'4','Pies');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('9','Daisy','Collie','Female','Dostepny','9',to_date('24/06/10','RR/MM/DD'),'2','Pies');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('10','Shadow','Mieszaniec','Male','Dostepny','10',to_date('24/10/02','RR/MM/DD'),'7','Pies');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('11','Mimi','Mieszañec','Female','Dostepny','11',to_date('24/10/01','RR/MM/DD'),'2','Kot');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('12','Tina','Mieszañec','Female','Dostepny','12',to_date('24/09/15','RR/MM/DD'),'3','Kot');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('13','Tommy','Mieszañec','Male','Dostepny','13',to_date('24/07/20','RR/MM/DD'),'4','Kot');
Insert into SCHRONISKO.ZWIERZETA (ID,IMIE,RASA,PLEC,STATUS,KOJEC_ID,DATA_PRZYJECIA,WIEK,TYP) values ('14','Lizak','Mieszaniec','Male','Dostepny','9',to_date('24/11/06','RR/MM/DD'),'13','Pies');
--------------------------------------------------------
--  DDL for Index SYS_C008274
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008274" ON "SCHRONISKO"."KOJCE" ("KOJEC_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008277
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008277" ON "SCHRONISKO"."ADRESY" ("ID_ADRESU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008279
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008279" ON "SCHRONISKO"."DARCZYNCY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008280
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008280" ON "SCHRONISKO"."DARCZYNCY" ("NAZWA_UZYTKOWNIKA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008281
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008281" ON "SCHRONISKO"."DARCZYNCY" ("MAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008284
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008284" ON "SCHRONISKO"."REJESTR_DAROWIZN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008292
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008292" ON "SCHRONISKO"."PRACOWNICY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008294
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008294" ON "SCHRONISKO"."ZWIERZETA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008298
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008298" ON "SCHRONISKO"."REJESTR_ADOPCJI" ("ID_ADOPCJI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008302
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008302" ON "SCHRONISKO"."PRACOWNIK_ZWIERZETA" ("PRACOWNIK_ID", "ZWIERZE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008277
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008277" ON "SCHRONISKO"."ADRESY" ("ID_ADRESU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008279
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008279" ON "SCHRONISKO"."DARCZYNCY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008280
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008280" ON "SCHRONISKO"."DARCZYNCY" ("NAZWA_UZYTKOWNIKA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008281
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008281" ON "SCHRONISKO"."DARCZYNCY" ("MAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008274
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008274" ON "SCHRONISKO"."KOJCE" ("KOJEC_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008292
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008292" ON "SCHRONISKO"."PRACOWNICY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008302
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008302" ON "SCHRONISKO"."PRACOWNIK_ZWIERZETA" ("PRACOWNIK_ID", "ZWIERZE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008298
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008298" ON "SCHRONISKO"."REJESTR_ADOPCJI" ("ID_ADOPCJI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008284
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008284" ON "SCHRONISKO"."REJESTR_DAROWIZN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008294
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHRONISKO"."SYS_C008294" ON "SCHRONISKO"."ZWIERZETA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Procedure DODAJ_ADOPCJE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHRONISKO"."DODAJ_ADOPCJE" (
    id_zwierzecia IN NUMBER,
    id_pracownika IN NUMBER,
    id_adresu IN NUMBER,
    data_adopcji IN DATE,
    imie IN VARCHAR2,
    nazwisko IN VARCHAR2,
    numer_telefonu IN VARCHAR2
) AS
BEGIN
    -- Wstawianie danych do tabeli REJESTR_ADOPCJI
    INSERT INTO REJESTR_ADOPCJI (
        ID_ADOPCJI,
        ZWIERZE_ID,
        PRACOWNIK_ID,
        ADRES_ID,
        DATA_ADOPCJI,
        IMIE,
        NAZWISKO,
        NUMER_TELEFONU
    ) VALUES (
        seq_adopcje_id.NEXTVAL, -- Automatyczne przypisywanie ID
        id_zwierzecia,
        id_pracownika,
        id_adresu,
        data_adopcji,
        imie,
        nazwisko,
        numer_telefonu
    );

    -- Zatwierdzenie transakcji
    COMMIT;

END;

/
--------------------------------------------------------
--  DDL for Procedure DODAJ_ADRES
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHRONISKO"."DODAJ_ADRES" (
    p_miasto VARCHAR2,
    p_kod_pocztowy VARCHAR2,
    p_ulica VARCHAR2,
    p_numer_domu VARCHAR2,
    p_numer_mieszkania VARCHAR2
) AS
BEGIN
    INSERT INTO Adresy (
        ID_ADRESU, 
        MIASTO, 
        KOD_POCZTOWY, 
        ULICA, 
        NUMER_DOMU, 
        NUMER_MIESZKANIA
    )
    VALUES (
        Adresy_seq.NEXTVAL, 
        p_miasto, 
        p_kod_pocztowy, 
        p_ulica, 
        CASE WHEN p_numer_domu IS NULL OR p_numer_domu = '' THEN NULL ELSE p_numer_domu END, 
        CASE WHEN p_numer_mieszkania IS NULL OR p_numer_mieszkania = '' THEN NULL ELSE p_numer_mieszkania END
    );
    COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Procedure DODAJ_PRACOWNIKA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHRONISKO"."DODAJ_PRACOWNIKA" (
    p_imie VARCHAR2,
    p_nazwisko VARCHAR2,
    p_pensja NUMBER,
    p_stanowisko VARCHAR2,
    p_adres_id NUMBER,
    p_data_zatrudnienia DATE
) AS
BEGIN
    INSERT INTO Pracownicy (ID, IMIE, NAZWISKO, PENSJA, STANOWISKO, ADRES_ID, DATA_ZATRUDNIENIA)
    VALUES (Pracownicy_seq.NEXTVAL, p_imie, p_nazwisko, p_pensja, p_stanowisko, p_adres_id, p_data_zatrudnienia);
    COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Procedure DODAJ_ZWIERZE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHRONISKO"."DODAJ_ZWIERZE" (
    p_imie          VARCHAR2,
    p_rasa           VARCHAR2,
    p_plec           VARCHAR2,
    p_status         VARCHAR2,
    p_kojec_id       NUMBER,
    p_data_przyjecia DATE,
    p_wiek           NUMBER,
    p_typ            VARCHAR2
) AS
BEGIN
    INSERT INTO ZWIERZETA (
        ID, IMIE, RASA, PLEC, STATUS, KOJEC_ID, DATA_PRZYJECIA, WIEK, TYP
    ) 
    VALUES (
        ZWIERZETA_SEQ.NEXTVAL, p_imie, p_rasa, p_plec, p_status, p_kojec_id, p_data_przyjecia, p_wiek, p_typ
    );
    COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Procedure EDYTUJ_ADRES
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHRONISKO"."EDYTUJ_ADRES" (
    p_id_adresu NUMBER,
    p_miasto VARCHAR2,
    p_kod_pocztowy VARCHAR2,
    p_ulica VARCHAR2,
    p_numer_domu VARCHAR2,
    p_numer_mieszkania VARCHAR2
) AS
BEGIN
    UPDATE Adresy
    SET MIASTO = p_miasto,
        KOD_POCZTOWY = p_kod_pocztowy,
        ULICA = p_ulica,
        NUMER_DOMU = p_numer_domu,
        NUMER_MIESZKANIA = p_numer_mieszkania
    WHERE ID_ADRESU = p_id_adresu;
    COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Procedure EDYTUJ_PRACOWNIKA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHRONISKO"."EDYTUJ_PRACOWNIKA" (
    p_id NUMBER,
    p_imie VARCHAR2,
    p_nazwisko VARCHAR2,
    p_pensja NUMBER,
    p_stanowisko VARCHAR2,
    p_adres_id NUMBER,
    p_data_zatrudnienia DATE
) AS
BEGIN
    UPDATE Pracownicy
    SET IMIE = p_imie,
        NAZWISKO = p_nazwisko,
        PENSJA = p_pensja,
        STANOWISKO = p_stanowisko,
        ADRES_ID = p_adres_id,
        DATA_ZATRUDNIENIA = p_data_zatrudnienia
    WHERE ID = p_id;
    COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Procedure EDYTUJ_ZWIERZE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHRONISKO"."EDYTUJ_ZWIERZE" (
    p_id_zwierzecia NUMBER,
    p_imie VARCHAR2,
    p_rasa VARCHAR2,
    p_plec VARCHAR2,
    p_status VARCHAR2,
    p_kojec_id NUMBER,
    p_data_przyjecia DATE,
    p_wiek NUMBER,
    p_typ VARCHAR2
) AS
BEGIN
    UPDATE Zwierzeta
    SET IMIE = p_imie,
        RASA = p_rasa,
        PLEC = p_plec,
        STATUS = p_status,
        KOJEC_ID = p_kojec_id,
        DATA_PRZYJECIA = p_data_przyjecia,
        WIEK = p_wiek,
        TYP = p_typ
    WHERE ID = p_id_zwierzecia;
    COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Procedure USUN_ADOPCJE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHRONISKO"."USUN_ADOPCJE" (
    p_id NUMBER
) AS
BEGIN
    -- Usuwamy rekord z tabeli REJESTR_ADOPCJI na podstawie ID adopcji
    DELETE FROM REJESTR_ADOPCJI WHERE ID_ADOPCJI = p_id;

    -- Zatwierdzamy transakcjê
    COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Procedure USUN_ADRES
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHRONISKO"."USUN_ADRES" (
    p_id NUMBER
) AS
BEGIN
    DELETE FROM Adresy WHERE ID_ADRESU = p_id;
    COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Procedure USUN_PRACOWNIKA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHRONISKO"."USUN_PRACOWNIKA" (
    p_id NUMBER
) AS
BEGIN
    DELETE FROM Pracownicy WHERE ID = p_id;
    COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Procedure USUN_ZWIERZE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCHRONISKO"."USUN_ZWIERZE" (
    p_id NUMBER
) AS
BEGIN
    DELETE FROM Zwierzeta WHERE ID = p_id;
    COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Function GET_ADDRESSES
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "SCHRONISKO"."GET_ADDRESSES" 
RETURN SYS_REFCURSOR
IS
    address_cursor SYS_REFCURSOR;
BEGIN
    OPEN address_cursor FOR
    SELECT 
        ID_ADRESU, 
        MIASTO, 
        KOD_POCZTOWY, 
        ULICA, 
        NUMER_DOMU, 
        NUMER_MIESZKANIA 
    FROM Adresy;

    RETURN address_cursor;
END;

/
--------------------------------------------------------
--  DDL for Function GET_ADOPTION_DETAILS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "SCHRONISKO"."GET_ADOPTION_DETAILS" 
RETURN SYS_REFCURSOR
IS
    adoption_cursor SYS_REFCURSOR;
BEGIN
    OPEN adoption_cursor FOR
    SELECT 
        ra.ID_ADOPCJI, 
        z.IMIE || ' (' || z.RASA || ')' || ' - ' || k.NUMER AS ZWIERZE, 
        p.IMIE || ' ' || p.NAZWISKO AS PRACOWNIK, 
        ad.MIASTO || ', ' || ad.KOD_POCZTOWY || ', ' || ad.ULICA || ' ' || ad.NUMER_DOMU || COALESCE('/' || ad.NUMER_MIESZKANIA, '') AS ADRES, 
        ra.DATA_ADOPCJI, 
        ra.imie || ' ' || ra.nazwisko || ' ' || ra.numer_telefonu AS DANE_ADOPTUJACEGO
    FROM REJESTR_ADOPCJI ra
    LEFT JOIN PRACOWNICY p ON ra.PRACOWNIK_ID = p.ID
    LEFT JOIN ZWIERZETA z ON ra.ZWIERZE_ID = z.ID
    LEFT JOIN KOJCE k ON z.KOJEC_ID = k.KOJEC_ID
    LEFT JOIN ADRESY ad ON ra.ADRES_ID = ad.ID_ADRESU;

    RETURN adoption_cursor;
END;

/
--------------------------------------------------------
--  DDL for Function GET_ADRESY
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "SCHRONISKO"."GET_ADRESY" 
RETURN SYS_REFCURSOR
IS
    adresy_cursor SYS_REFCURSOR;
BEGIN
    OPEN adresy_cursor FOR
    SELECT ID_ADRESU, MIASTO, KOD_POCZTOWY, ULICA, NUMER_DOMU, NUMER_MIESZKANIA 
    FROM Adresy;

    RETURN adresy_cursor;
END;

/
--------------------------------------------------------
--  DDL for Function GET_ANIMALS_AND_CAGES
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "SCHRONISKO"."GET_ANIMALS_AND_CAGES" 
RETURN SYS_REFCURSOR
IS
    animal_cursor SYS_REFCURSOR;
BEGIN
    OPEN animal_cursor FOR
    SELECT z.ID, z.IMIE, z.RASA, z.PLEC, z.STATUS, k.NUMER, z.DATA_PRZYJECIA, z.WIEK, z.TYP 
    FROM Zwierzeta z
    LEFT JOIN KOJCE k ON z.KOJEC_ID = k.KOJEC_ID;

    RETURN animal_cursor;
END;

/
--------------------------------------------------------
--  DDL for Function GET_AVAILABLE_ANIMALS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "SCHRONISKO"."GET_AVAILABLE_ANIMALS" 
RETURN SYS_REFCURSOR
IS
    result_cursor SYS_REFCURSOR;
BEGIN
    OPEN result_cursor FOR
    SELECT z.ID, z.IMIE, z.RASA, k.NUMER 
    FROM ZWIERZETA z
    LEFT JOIN KOJCE k ON z.KOJEC_ID = k.KOJEC_ID
    WHERE z.STATUS = 'Dostepny';

    RETURN result_cursor;
END;

/
--------------------------------------------------------
--  DDL for Function GET_FORMATTED_ADDRESSES
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "SCHRONISKO"."GET_FORMATTED_ADDRESSES" 
RETURN SYS_REFCURSOR
IS
    result_cursor SYS_REFCURSOR;
BEGIN
    OPEN result_cursor FOR
    SELECT 
        ID_ADRESU, 
        MIASTO || ', ' || KOD_POCZTOWY || ', ' || ULICA || ' ' || NUMER_DOMU || 
        CASE WHEN NUMER_MIESZKANIA IS NOT NULL THEN '/' || NUMER_MIESZKANIA ELSE '' END AS FULL_ADDRESS
    FROM Adresy;

    RETURN result_cursor;
END;

/
--------------------------------------------------------
--  DDL for Function GET_KOJCE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "SCHRONISKO"."GET_KOJCE" 
RETURN SYS_REFCURSOR
IS
    kojec_cursor SYS_REFCURSOR;
BEGIN
    OPEN kojec_cursor FOR
    SELECT KOJEC_ID, NUMER
    FROM KOJCE;

    RETURN kojec_cursor;
END;

/
--------------------------------------------------------
--  DDL for Function GET_KOORDYNATORZY_ADOPCJI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "SCHRONISKO"."GET_KOORDYNATORZY_ADOPCJI" 
RETURN SYS_REFCURSOR
IS
    result_cursor SYS_REFCURSOR;
BEGIN
    OPEN result_cursor FOR
        SELECT ID, IMIE, NAZWISKO 
        FROM Pracownicy 
        WHERE STANOWISKO = 'Koordynator Adopcji';

    RETURN result_cursor;
END;

/
--------------------------------------------------------
--  DDL for Function GET_PRACOWNICY_WITH_ADDRESS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "SCHRONISKO"."GET_PRACOWNICY_WITH_ADDRESS" 
RETURN SYS_REFCURSOR
IS
    result_cursor SYS_REFCURSOR;
BEGIN
    OPEN result_cursor FOR
    SELECT 
        p.ID, 
        p.IMIE, 
        p.NAZWISKO, 
        p.PENSJA, 
        p.STANOWISKO, 
        a.ULICA || ' ' || a.NUMER_DOMU || COALESCE('/' || a.NUMER_MIESZKANIA, '') || ', ' || a.MIASTO || ', ' || a.KOD_POCZTOWY AS FULL_ADDRESS, 
        p.DATA_ZATRUDNIENIA
    FROM Pracownicy p
    LEFT JOIN Adresy a ON p.ADRES_ID = a.ID_ADRESU;

    RETURN result_cursor;
END;

/
--------------------------------------------------------
--  Constraints for Table ADRESY
--------------------------------------------------------

  ALTER TABLE "SCHRONISKO"."ADRESY" MODIFY ("MIASTO" NOT NULL ENABLE);
  ALTER TABLE "SCHRONISKO"."ADRESY" MODIFY ("KOD_POCZTOWY" NOT NULL ENABLE);
  ALTER TABLE "SCHRONISKO"."ADRESY" ADD PRIMARY KEY ("ID_ADRESU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DARCZYNCY
--------------------------------------------------------

  ALTER TABLE "SCHRONISKO"."DARCZYNCY" MODIFY ("NAZWA_UZYTKOWNIKA" NOT NULL ENABLE);
  ALTER TABLE "SCHRONISKO"."DARCZYNCY" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCHRONISKO"."DARCZYNCY" ADD UNIQUE ("NAZWA_UZYTKOWNIKA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCHRONISKO"."DARCZYNCY" ADD UNIQUE ("MAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KOJCE
--------------------------------------------------------

  ALTER TABLE "SCHRONISKO"."KOJCE" ADD PRIMARY KEY ("KOJEC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRACOWNICY
--------------------------------------------------------

  ALTER TABLE "SCHRONISKO"."PRACOWNICY" MODIFY ("IMIE" NOT NULL ENABLE);
  ALTER TABLE "SCHRONISKO"."PRACOWNICY" MODIFY ("NAZWISKO" NOT NULL ENABLE);
  ALTER TABLE "SCHRONISKO"."PRACOWNICY" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRACOWNIK_ZWIERZETA
--------------------------------------------------------

  ALTER TABLE "SCHRONISKO"."PRACOWNIK_ZWIERZETA" ADD PRIMARY KEY ("PRACOWNIK_ID", "ZWIERZE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REJESTR_ADOPCJI
--------------------------------------------------------

  ALTER TABLE "SCHRONISKO"."REJESTR_ADOPCJI" MODIFY ("DATA_ADOPCJI" NOT NULL ENABLE);
  ALTER TABLE "SCHRONISKO"."REJESTR_ADOPCJI" ADD PRIMARY KEY ("ID_ADOPCJI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REJESTR_DAROWIZN
--------------------------------------------------------

  ALTER TABLE "SCHRONISKO"."REJESTR_DAROWIZN" MODIFY ("KWOTA" NOT NULL ENABLE);
  ALTER TABLE "SCHRONISKO"."REJESTR_DAROWIZN" MODIFY ("DATA" NOT NULL ENABLE);
  ALTER TABLE "SCHRONISKO"."REJESTR_DAROWIZN" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ZWIERZETA
--------------------------------------------------------

  ALTER TABLE "SCHRONISKO"."ZWIERZETA" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRACOWNICY
--------------------------------------------------------

  ALTER TABLE "SCHRONISKO"."PRACOWNICY" ADD FOREIGN KEY ("ADRES_ID")
	  REFERENCES "SCHRONISKO"."ADRESY" ("ID_ADRESU") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRACOWNIK_ZWIERZETA
--------------------------------------------------------

  ALTER TABLE "SCHRONISKO"."PRACOWNIK_ZWIERZETA" ADD FOREIGN KEY ("PRACOWNIK_ID")
	  REFERENCES "SCHRONISKO"."PRACOWNICY" ("ID") ENABLE;
  ALTER TABLE "SCHRONISKO"."PRACOWNIK_ZWIERZETA" ADD FOREIGN KEY ("ZWIERZE_ID")
	  REFERENCES "SCHRONISKO"."ZWIERZETA" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REJESTR_ADOPCJI
--------------------------------------------------------

  ALTER TABLE "SCHRONISKO"."REJESTR_ADOPCJI" ADD FOREIGN KEY ("ZWIERZE_ID")
	  REFERENCES "SCHRONISKO"."ZWIERZETA" ("ID") ENABLE;
  ALTER TABLE "SCHRONISKO"."REJESTR_ADOPCJI" ADD FOREIGN KEY ("PRACOWNIK_ID")
	  REFERENCES "SCHRONISKO"."PRACOWNICY" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REJESTR_DAROWIZN
--------------------------------------------------------

  ALTER TABLE "SCHRONISKO"."REJESTR_DAROWIZN" ADD FOREIGN KEY ("DARCZYNCA_ID")
	  REFERENCES "SCHRONISKO"."DARCZYNCY" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ZWIERZETA
--------------------------------------------------------

  ALTER TABLE "SCHRONISKO"."ZWIERZETA" ADD FOREIGN KEY ("KOJEC_ID")
	  REFERENCES "SCHRONISKO"."KOJCE" ("KOJEC_ID") ENABLE;


--------------------------------------------------------
--	TUTAJ KOD DOPISANY PRZEZ LUKASZA
--------------------------------------------------------


CREATE SEQUENCE  "SCHRONISKO"."DARCZYNCY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 64 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
/


create or replace PROCEDURE "DODAJ_DARCZYNCE" (
    p_nazwa_uzytkownika     VARCHAR2,
    p_imie                  VARCHAR2,
    p_nazwisko              VARCHAR2,
    p_mail                  VARCHAR2
) AS 
BEGIN
    INSERT INTO DARCZYNCY (
        ID, NAZWA_UZYTKOWNIKA, IMIE, NAZWISKO, MAIL
    )
    VALUES (
        DARCZYNCY_SEQ.NEXTVAL, p_nazwa_uzytkownika, P_imie, p_nazwisko, p_mail
    );
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001, 'B³¹d w procedurze DODAJ_DARCZYNCE: ' || SQLERRM);
END DODAJ_DARCZYNCE;
/



CREATE OR REPLACE PROCEDURE EDYTUJ_DARCZYNCE (
    p_id                  NUMBER,
    p_nazwa_uzytkownika   VARCHAR2,
    p_imie                VARCHAR2,
    p_nazwisko            VARCHAR2,
    p_mail                VARCHAR2
) AS
BEGIN
    UPDATE DARCZYNCY
    SET 
        NAZWA_UZYTKOWNIKA = p_nazwa_uzytkownika,
        IMIE              = p_imie,
        NAZWISKO          = p_nazwisko,
        MAIL              = p_mail
    WHERE 
        ID = p_id;

    COMMIT;
END EDYTUJ_DARCZYNCE;
/


CREATE OR REPLACE PROCEDURE USUN_DARCZYNCE (
    p_id NUMBER
) AS
BEGIN
    DELETE FROM DARCZYNCY
    WHERE ID = p_id;

    COMMIT;
END USUN_DARCZYNCE;
/


create or replace FUNCTION              "GET_DARCZYNCY" 
RETURN SYS_REFCURSOR
IS
    darczyncy_cursor SYS_REFCURSOR;
BEGIN
    OPEN darczyncy_cursor FOR
    SELECT 
        ID, 
        NAZWA_UZYTKOWNIKA, 
        IMIE, 
        NAZWISKO, 
        MAIL 
    FROM darczyncy;

    RETURN darczyncy_cursor;
END;
/







CREATE SEQUENCE  "SCHRONISKO"."DAROWIZNY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 31 CACHE 25 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;
/

CREATE OR REPLACE PROCEDURE DODAJ_DAROWIZNE (
    p_darczynca_id IN NUMBER,
    p_kwota IN NUMBER,
    p_data IN DATE
) AS
BEGIN
    -- Wstawienie nowego rekordu do tabeli REJESTR_DAROWIZN
    INSERT INTO SCHRONISKO.REJESTR_DAROWIZN (ID, DARCZYNCA_ID, KWOTA, DATA)
    VALUES (DAROWIZNY_SEQ.NEXTVAL, p_darczynca_id, p_kwota, p_data);

    -- Zatwierdzenie transakcji
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        -- Obs³uga b³êdów
        ROLLBACK;
        RAISE;
END;
/


CREATE OR REPLACE PROCEDURE EDYTUJ_DAROWIZNE (
    p_id IN NUMBER,
    p_darczynca_id IN NUMBER,
    p_kwota IN NUMBER,
    p_data IN DATE
) AS
BEGIN
    -- Aktualizacja rekordu w tabeli REJESTR_DAROWIZN
    UPDATE SCHRONISKO.REJESTR_DAROWIZN
    SET DARCZYNCA_ID = p_darczynca_id,
        KWOTA = p_kwota,
        DATA = p_data
    WHERE ID = p_id;

    -- Sprawdzenie, czy rekord zosta³ zaktualizowany
    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Nie znaleziono darowizny o podanym ID.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/


CREATE OR REPLACE PROCEDURE USUN_DAROWIZNE (
    p_id IN NUMBER
) AS
BEGIN
    -- Usuniêcie rekordu z tabeli REJESTR_DAROWIZN
    DELETE FROM SCHRONISKO.REJESTR_DAROWIZN
    WHERE ID = p_id;

    -- Sprawdzenie, czy rekord zosta³ usuniêty
    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'Nie znaleziono darowizny o podanym ID.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

BEGIN
    DODAJ_DARCZYNCE('jan_kowalski', 'Jan', 'Kowalski', 'jan.kowalski@example.com');
    DODAJ_DARCZYNCE('anna_nowak', 'Anna', 'Nowak', 'anna.nowak@example.com');
    DODAJ_DARCZYNCE('piotr_wisniewski', 'Piotr', 'Wisniewski', 'piotr.wisniewski@example.com');
    DODAJ_DARCZYNCE('katarzyna_kaminska', 'Katarzyna', 'Kaminska', 'katarzyna.kaminska@example.com');
    DODAJ_DARCZYNCE('michal_wojcik', 'Michal', 'Wojcik', 'michal.wojcik@example.com');
    DODAJ_DARCZYNCE('ewa_kaczmarek', 'Ewa', 'Kaczmarek', 'ewa.kaczmarek@example.com');
    DODAJ_DARCZYNCE('tomasz_lewandowski', 'Tomasz', 'Lewandowski', 'tomasz.lewandowski@example.com');
    DODAJ_DARCZYNCE('joanna_zielinska', 'Joanna', 'Zielinska', 'joanna.zielinska@example.com');
    DODAJ_DARCZYNCE('robert_szymanski', 'Robert', 'Szymanski', 'robert.szymanski@example.com');
    DODAJ_DARCZYNCE('maria_wozniak', 'Maria', 'Wozniak', 'maria.wozniak@example.com');
END;
/
